### ISSUE TITLE
Usar Github issues como plataforma para colaboración

### ISSUE THREAD

**Issue by jeduan** [javascriptmx/chelajs#1]
Los sistemas de organización de equipos por excelencia son Trello, Asana, Pivotal y similares, sin embargo he estado usando sólo Github como método para comunicarme con un equipo remoto y ha funcionado bien tanto como Kanban, como para reportar tiempo.

Quiero dar ejemplos de cómo organizar a un equipo.

**Comment by omarsharim** [comment]
¿Phabricator ya fue considerado(http://phabricator.org/)? para la organización y toda la ing. de software me ha ido bastante bien.

**Comment by pateketrueke** [comment]
> Quiero dar ejemplos de cómo organizar a un equipo.

:+1:

**Comment by SergioMartinezP** [comment]
+1

**Comment by Siedrix** [comment]
+1

**Comment by bleedingxedge** [comment]
+1

**Comment by unRob** [comment]
Igual se puede incluir cómo organizar comunidades via github, cómo, pues, ¿esta? ¿Te animas @jeduan ?

**Comment by rctorr** [comment]
+1

**Comment by code4jhon** [comment]
+1

**Comment by unRob** [comment]
Mark-to-sweep por falta de ponentes, este issue se cerrará en 30 días salvo que alguno de los interesados guste adoptarlo.
