### ISSUE TITLE
Programar bots de Slack

### ISSUE THREAD

**Issue by Sparragus** [javascriptmx/chelajs#10]
Puedo dar una plática de como hacer bots para Slack. ¿Qué les parece? :D

**Comment by jeduan** [comment]
:+1:

**Comment by bleedingxedge** [comment]
+1!!!111

**Comment by Sparragus** [comment]
Podemos coordinarla para despues del 20 de julio. :) ¿Que les parece?

Un poco de credencial sobre el tema:

Kanye West interrumpe tus conversaciones:
http://ledhack.org/imma-let-you-finish/
Edward Snowden te ayuda a mantener tu anonimidad y privacidad en Slack:
http://ledhack.org/slack-bot-edward-snowden/

Como ven?



Richard Kaufman

**Comment by jeduan** [comment]
Ok, entonces tentativamente para el de Agosto que sería el 5 de Agosto

**Comment by Sparragus** [comment]
Sweet. Me confirman luego. :)

Richard Kaufman

2015-06-09 12:06 GMT-05:00 Jeduan Cornejo <notifications@github.com>:
