### ISSUE TITLE
Mandar tu aplicación de Node.js a producción con Ansible

### ISSUE THREAD

**Issue by MexicanHacker** [javascriptmx/chelajs#12]
Durante los ultimos meses he estado trabajando en la orquestación de una app de Node para mandarse a producción, me gustaría hablar de lo que se debe de hacer para preparar la app y los ambientes para producción y como difieren de un ambiente local, pero sobre todo como puedes hacerlo transparente con herramientas que faciliten esto como Ansible + Vagrant.

**Comment by jeduan** [comment]
Pero estarás en la ciudad de México?

**Comment by MexicanHacker** [comment]
Voy a andar por allá unos días de Agosto y quería ver cuando es la sesión, estaba apostando en que  coincidiera el evento con mi estadía. ¿Cuándo tienen planeado hacer las sesions tanto de Julio como Agosto?

**Comment by jeduan** [comment]
Siempre es el primer miércoles de cada mes

**Comment by MexicanHacker** [comment]
Bien, si voy a andar por allá el 5 de Agosto.
