### ISSUE TITLE
Ember.js, ember-cli y el futuro del framework

### ISSUE THREAD

**Issue by luismendozamx** [javascriptmx/chelajs#14]
## Ember.js

Este es un pequeño outline de los puntos que me gustaría tocar en la plática. Sé que son muchos, pero la idea sería un overview general del framework y lo que existe alrededor de éste. Lo que me interesa es mostrar todo lo que es posible con el ecosistema de herramientas que existen en torno a Ember y motivar a que la audiencia se eche un clavado más a fondo por su parte.

### Intro

* Filosofía y por qué utilizar Ember
  * SPA
  * MVC
  * Un framework para construir aplicaciones ambiciosas
* Historia y antecedentes
* El equipo detrás de Ember y su comunidad
* Quién utiliza Ember
  * Heroku, Vine, Zendesk, etc.

### Arquitectura de un app en Ember
* Estructura de la aplicación
* ES6 y Babel
* La estructura de pods

### No es solo un framework, es un ecosistema
* ember-cli
* ember-data
  * local storage adapter
  * Adaptadores y serializadores
* ember inspector
* ember addons

### Ember 2.0 y el futuro del framework
* Web components
* Las lecciones de React.js
* "Stability without stagnation"
  * El ciclo de releases de Ember
  * El camino hacia Ember 2.0

### Demo
* App para agendar meetups con un backend en Firebase

**Comment by unRob** [comment]
Me late tu propuesta Luis, pero me parece que el material que quieres cubrir es demasiado extenso. Las pláticas normalmente son de 20 minutos, creo que podrías elegir alguno de los puntos secundarios de tu outline y hacer una plática completa sobre esto, ¿qué te parece? Tal vez hasta podríamos hacer una cada mes. ¿Qué opinan @jeduan @Siedrix ?

**Comment by luismendozamx** [comment]
Gracia @unRob yo también creo que podría ser demasiado. Creo que dividirlo en más de una plática podría ser buena idea. Quizá empezar por Intro + Ecosistema (aquí mencionar la estructura general). Y dejar la parte de Ember 2.0 y un demo para otra plática posterior. ¿Qué les parece?

**Comment by unRob** [comment]
Perfecto, pero creo que nos podríamos enfocar en "_Un framework para construir aplicaciones ambiciosas_", tal vez contando porqué Ember es ideal en este sentido a manera de introducción. Creo que algo por el estilo sería un buen fit para el ciclo de pláticas, quizá Septiembre u Octubre.

**Comment by unRob** [comment]
Luis, ¿Cómo vas con tu idea, crees tener un outline mas avanzado? Creo que para Septiembre sería un poco acelerado, pero en Octubre podría quedar muy bien, ¿qué opinas?

**Comment by unRob** [comment]
Marco como abandonado el tema; si me das permiso @luismendozamx, lo ponemos como en búsqueda de ponente.

**Comment by luismendozamx** [comment]
Hola @unRob Perdón que no había contestado a esto. Hemos estado como locos y no había podido darle una revisada. ¿Cómo andan de pláticas para el meetup de diciembre? Si se puede me encantaría darle seguimiento y presentarla en el siguiente meetup.

**Comment by jeduan** [comment]
Creo que de Diciembre ya estamos a tope, pero Enero sigue super vacío. ¿Por qué no vamos trabajando con el outline y en una de esas enfocamos el evento de Enero a frontend?

**Comment by luismendozamx** [comment]
Gracias @jeduan me parece perfecto. Empiezo con el outline y les comparto el link del repo donde lo voy a poner.

**Comment by rogr** [comment]
@luismendozamx Te gustaría dar la platica en este chela.js? Si es así, si gustas te puedo ceder mi lugar. 
Apenas estoy escribiendo el outline de la mia y me darias mas tiempo de prepararla: https://github.com/javascriptmx/chelajs/issues/27

**Comment by unRob** [comment]
¿Has tenido chance de seguirle dando a tu plática @luismendozamx?

**Comment by Sparragus** [comment]
Dude, este tema está súper cool. Y no solo eso. Hay mucha banda en el tren del mame de React (incluyéndome) que nunca ha tratado más nada. [Estudiar otros frameworks es súper importante](https://twitter.com/dan_abramov/status/683771840100196352).

Enero aun tiene espacio. :) Te late darla entonces?

**Comment by luismendozamx** [comment]
@Sparragus Sí! Me encantaría darla en Enero. De hecho justo estoy trabajando en la presentación. @unRob perdón por no contestar antes, voy regresando de vacaciones. ¿Cuándo es el de enero? ¿Miércoles 6 o 13?

**Comment by Sparragus** [comment]
Miércoles 13

**Comment by luismendozamx** [comment]
Buenísimo! Yo 100% apuntado. Le hice unos cambios al outline original y estoy trabajando ya en la presentación. Va a estar aquí: http://luismendozamx.github.io/ember-intro

**Comment by luismendozamx** [comment]
El repo con la presentación es: https://github.com/luismendozamx/ember-intro por si quieren dejar algún comentario en específico. Entre hoy y mañana les aviso cuando esté ya más avanzada. Y me acabo de conectar al slack de javascriptmx por si quieren irme molestando por ahí.

**Comment by Sparragus** [comment]
Yeah!!!! Pronto te escribiremos al email que aparece en tu perfil para pedirte un poco más de info sobre la plática (título, mini-descripción, etc).

**Comment by luismendozamx** [comment]
Perfecto! Estoy al pendiente.
