### ISSUE TITLE
ECMAScript 6. What's new?

### ISSUE THREAD

**Issue by miguelcoba** [javascriptmx/chelajs#15]
Está platica es acerca de los nuevos features que ECMAScript 6 introduce, el soporte en browsers que existe actualmente.

**Comment by unRob** [comment]
Me late la idea, ¿nos puedes contar un poco mas? ¿Tú te animarías a darla? Creo que sería valioso también hablar un poco de lo que se está cocinando para ES2016/ES7, como `await`/`async` y los `decorators`, aunque chance sólo brevemente. ¿Qué opinas?

**Comment by miguelcoba** [comment]
Si, la idea es darla yo. La presentación ya la estoy creando, independientemente de si la presento en ChelaJS la voy a presentar internamente en nearsoft.com. El contenido será un breve repaso, de las más importantes features de ES6: classes, let, template strings, destructuring, modules, arrows y promises. No es posible ver todo muy a detalle, pero en general dar un ejemplo de cada uno y las ventajas para el desarrollador de tener esos features.

**Comment by unRob** [comment]
Excelente, creo que sería material buenísimo para el evento en Septiembre, ¿cómo ves?

**Comment by miguelcoba** [comment]
Perfecto

**Comment by jeduan** [comment]
Es un muy buen tema Miguel, definitivamente nos hace falta tocarlo.

Definitivamente el detalle va a estar en qué partes. Siempre tratamos de que en ChelaJS se complementen todos los blog posts que asumimos que los asistentes ya leyeron al respecto con experiencias del mundo real 

Si pudieras tener ejemplos de cosas que refactorizaste con ES6 en vez de ejemplos teóricos creo que los asistentes se llevarían mucho más a casa.

**Comment by miguelcoba** [comment]
Olvidé mandarles el link de los slides para que los vean.

https://github.com/miguelcoba/es6-features

**Comment by unRob** [comment]
Es un buen de material @miguelcoba, ¿crees que te de tiempo de presentarlo en ~20 minutos? Por otro lado, me da la impresión que está mas orientada a ser una clase interactiva que a una presentación, pero me gustó mucho la idea de hablar de "las ventajas para el desarrollador de tener esos features" que mencionas arriba, ¿qué opinas de condensar la plática en este segmento?

**Comment by miguelcoba** [comment]
No hay problema.
