### ISSUE TITLE
Node JS desde cero

### ISSUE THREAD

**Issue by fmagrosoto** [javascriptmx/chelajs#16]
Que tal.
Recomiendo dar un *mini taller express* de NODEjs desde cero.
Donde incluya desde como instalar, actualizar, desinstalar hasta cómo usar NPM, Bower, Grunt, pasando por cómo instalar Mongo y un ejemplo de caso práctico: "Cómo almacenar información de clientes", una aplicación para que desde consola podamos almacenar, extraer y modificar información rápida de nuestros clientes. Si yo dominara el tema, yo daría este curso dirigido a gente como yo que conocemos la tecnología pero nos hace falta que alguien nos diga "vas bien" o "es así". Saludos.

**Comment by unRob** [comment]
Creo que te gustaría venir a uno de los talleres de [nodeschool](http://nodeschool.io/mexicocity/) que organiza la comunidad, Fernando. Si tienes dudas concretas sobre estos temas, te puede interesar entrar al [chat](http://chat.javascriptmx.com) y ver que opina la comunidad.

Por ahora creo que un taller de esta naturaleza no es un buen fit para chelajs, en parte por el formato actual de 20 minutos por plática. Si te animas a aprender todo esto, para un próximo evento estaría buenazo tener tu perspectiva al respecto, y que nos cuentes que aprendiste de hacer un CRM en nodejs y MongoDB. ¿Qué te parece?

**Comment by unRob** [comment]
Cerrando propuesta ya que no hubo respuesta sobre el tema.

**Comment by fmagrosoto** [comment]
Me he metido a los talleres de Nodeschool, por cierto, gracias por la recomendación. Es cierto lo que dices, no hay forma de dar en 20 minutos un recorrido por Node. Pero sigo pensado - e insistiendo - en encontrar un curso con estas características. No foros, no chat, no cursos en línea; sino uno presencial y con un instructor que tenga ganas de enseñar (y de aprender, porque siempre se aprende algo, por lo menos, se aprende a enseñar). Si sabes de algo, si sabes de alguien... por favor avísame. Saludos.
