### ISSUE TITLE
React Hooks - cómo usarlos y escribirlos

### ISSUE THREAD

**Issue by kylebebak** [javascriptmx/chelajs#163]
### Sumario

[Hooks](https://reactjs.org/docs/hooks-intro.html) "let you use state and other React features without writing a class."

Hacen que function components tengan básicamente la misma funcionalidad que class components, pero con menos boilerplate. También dan una gran facilidad de compartir código complejo entre componentes.

Después de usar hooks durante un año, function components con hooks se me han vuelto igual de intuitivos como class components, y mucho más fáciles de escribir.

Me gustaría enseñarles cómo usar los hooks que vienen con React, y cómo combinarlos para crear tus propios hooks reutilizables.

### Outline

- resumen de hooks
  + hooks básicos: `useState`, `useEffect`, `useRef`, `useCallback`
- cómo combinar hooks básicos para crear tus propios hooks
  + ejemplos de custom hooks, y para qué usarlos
- cómo usar ciertos hooks en class components
  + cuáles son los requisitos para usarlos así?

### Beneficios

- Usar todos los features de class components en tus function components
- Controlar los efectos de `componentDidMount`, `componentDidUpdate`, y `componentWillUnmount` en sólo lugar
- Empaquetar funcionalidad compleja para que se pueda reutilizar en varios componentes

### Cuándo

En marzo si se puede!

```yaml
name: Kyle Bebak
url: https://github.com/kylebebak
pic: https://dronfelipe.com/images/img/face.png
bio: Ciclista kamikaze
```

**Comment by jmz7v** [comment]
Hola @kylebebak !

Te gustaría presentar el próximo miércoles 4 de marzo?

**Comment by kylebebak** [comment]
Hola Julio, me encantaría!

**Comment by jmz7v** [comment]
Kyle, muchas gracias por tu charla en Eventloop! 🙌

Estamos en contacto 😁

Edit: Software Gurú ya publicó el video de la charla en YouTube

https://youtu.be/BB7AV-KPjj8

**Comment by kylebebak** [comment]
De nada @jmz7v , fue un placer. Y gracias por mandarme el vídeo!

Hablamos pronto, cuídate
