### ISSUE TITLE
Pruebas de Estrés

### ISSUE THREAD

**Issue by SergioMartinezP** [javascriptmx/chelajs#17]
el asunto es hablar de lo que es una prueba de estrés, y cómo se puede realizar usando jMeter que es OpenSource, o ¿qué herramienta utilizan para hacer pruebas de estrés?

**Comment by unRob** [comment]
Me late la idea, pero me gustaría saber mas detalles. ¿Porqué es importante hacer pruebas de estrés a una aplicación en JS? ¿Sólo es útil para medir el performance del backend, o es importante/posible hacer pruebas al rendering? ¿Porqué usar JMeter en vez de las herramientas del browser?

Estaría chido si te puedes armar un outline super breve de la plática que tienes en mente, me gustaría armar un evento sobre tooling al rededor del ecosistema!

**Comment by SergioMartinezP** [comment]
Ok, las pruebas de estrés sólo hacen sentido contra el Backend, las pruebas al rendering entran más en integración, o aceptación, o algo de ese estilo.

Lo que voy a hacer estos días es revisar que otras herramientas pueden utilizarse, y sobre eso proponer sobre cual herramienta mostrar. 

y ya con eso pongo un outline de la platica

**Comment by unRob** [comment]
¿Cómo vamos con esto Serch?

**Comment by SergioMartinezP** [comment]
Ya estuve revisando algunas otras y pues creo que sigo con jMeter, espero a mas tardar el Lunes poner un outline a ver que te parece.

**Comment by SergioMartinezP** [comment]
Los puntos a tratar son:

¿Qué es una prueba de estrés? (definición, propósito)
-Acciones que parecen pruebas de estrés pero... (miles de peticiones vs 1 url, lista de urls, scripts)
-Diseño de una prueba de estrés (ancho de banda, múltiples usuarios, caches, contención en la escritura, escalabilidad)
-Demo con Apache JMeter 

Me parece que así tendremos un panorama general de las pruebas de estrés al backend.

**Comment by unRob** [comment]
Me gusta por dónde vas, pero te quiero proponer un outline basado en el tuyo; te propongo estos ajustes para tener un demo mas fluido, mientras repasas cada una de las condiciones a tratar. Creo que la conclusión es importante, por eso agregué el último punto, donde chance nos puedes hablar un poco de qué técnicas usarías si tu aplicación objetivo está corriendo sobre nodejs.

- ¿Qué es una prueba de estrés?
  - ¿Para qué las hacemos?
  - ¿Qué no constituye una prueba de estrés?
- ¿Cómo la implemento? / Demo
  - Ancho de banda
  - múltiples usuarios
  - caches
  - contención en la escritura
  - escalabilidad
- Usando los resultados
  - ¿Qué acciones tomé en consecuencia?
  - ¿En qué resultaron mis acciones?
  - ¿Cuándo es momento para hacer estas pruebas?

¿Qué opinas? Me gustaría ir agendando esta charla para un evento próximo, ¿cuándo te gustaría presentar?

**Comment by SergioMartinezP** [comment]
Me parece interesante este outline; por la duración de la platica y el echo que el demo lo haría en una lap, lo pondría justo antes de llegar a la conclusión, pues mientras va "corriendo" puedo mencionar las conclusiones. Puede ser para este o para el próximo, sin problemas.

**Comment by Sparragus** [comment]
Sé que no es mi plática, pero quiero recomendarte fuertemente que no hagas
ningun tipo de programación en vivo, incluyendo correr demos. Todo eso
suele fallar, además de ponerte presión a la hora de presentar. Mejor idea
es que lleves screencasts, screenshots, fotos, videos, etc.

Por experiencia aprendí que cuando quiero presentar la ejecución de un app
en una presentación estilo ChelaJS, mejor hago un screencast unos días
antes, y enseño ese video. Funciona súper bien y te evitas cualquier
desastre. Recuerda  la ley de murphy. :D

Otra razón para evitar eso es que las pláticas de ChelaJS se graban y se
publican en YouTube. Es más seguro que corras un video que tienes en tu
computadora, a tener que estar cambiando de ventanas, correr tu app, rezar
por que el internet funcione y que todo funcione.

Y una última razón es que como veras, cada plática solo tiene como 20
minutos. Los videos/imagenes aseguran que no pierdas tiempo resolviendo
problemas.

Y te lo digo por experiencia. Ena vez estaba dando un taller de express,
pero tres dias antes de mi presentación, Express había pasado de las
version 3 a las versión 4.0.0.

Comienzo mi live coding con `npm install --save express` y mi siguiente
paso ya no funcionaba por que ahora express se usaba de otra forma. (razón:
El express-generator ya no estaba integrado y yo no me había enterado) Tuve
que meterme a Google. No fue muy cool eso.

Realmente no es que quiera interferir con tu presentación, es solo una
sugerencia. :D


Richard Kaufman

2015-09-29 20:18 GMT-05:00 Sergio Martínez <notifications@github.com>:

**Comment by SergioMartinezP** [comment]
Gracias @Sparragus, el "demo" es sólo para mostrar como se ve un producto (JMeter) trabajando, y es totalmente local, precisamente por que podría fallar el internet o dar resultados impredecibles por el ancho de banda.

**Comment by Sparragus** [comment]
👌🏼

Richard Kaufman

2015-09-30 16:04 GMT-05:00 Sergio Martínez <notifications@github.com>:
