### ISSUE TITLE
App scaffolding y generadores de proyectos en JS

### ISSUE THREAD

**Issue by betolink** [javascriptmx/chelajs#18]
Hola, estaré la primera semana de Septiembre en el DF y estaba pensando en dar una charla de como estructurar proyectos básicos y como usar generadores para facilitar el desarrollo en JS (usando Yeoman).  Si les interesa nos coordinamos.

**Comment by Sparragus** [comment]
Uuuuu! Este tema me interesa mucho.

On Sunday, August 9, 2015, Beto <notifications@github.com> wrote:

> Hola, estaré la primera semana de Septiembre en el DF y estaba pensando en
> dar ua charla de como estructurar proyectos básicos y como usar generadores
> para facilitar el desarrollo en JS (usando Yeoman). Si les interesa nos
> coordinamos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/18>.
>


-- 
Richard Kaufman

**Comment by unRob** [comment]
Gracias por la propuesta Beto, me parece interesante la propuesta, ¿qué te parecería contarnos las razones detrás de seguir estos patrones de organización y sobre eso hablar de cuales son y cómo se usan?

**Comment by betolink** [comment]
Hola, cada framework tiene sus convenciones y "best practices", una de estas convenciones es como organizar el contenido en cada aplicación, eg. nuestro código, librerias propias, librerias de terceros, recursos etc. Estos patrones para organizar una app varían dependiendo del tipo de app que estemos desarrollando. En JS los factores más importantes que dictan que tipo de scaffolding debemos usar son:

* **Tamaño de la app**: simple o modular, 
* **Plataforma**: movil, web, app hibrida
* **Target**:  servidor, cliente.
* **Framework**: Backbone, Flux, MEAN, etc.
* **Paradigma**:  MVC, MV, Flux etc.

Ahora lo interesante de esto es que no tenemos que hacerlo todo manualmente, este es el propósito de los generadores de proyectos como Yeoman, que nos ayuda a comenzar un proyecto generando un template que en la mayoría de los casos sigue las mejores prácticas para organizar los contenidos de la app. Yeoman tiene generadores oficiales y desarrollados por la comunidad, cualquiera de nosotros podría hacer uno y usarlo.

Por ejemplo, si quisieramos hacer una pagina sencilla usando **Backbone** lo primero sería instalar Yeoman y el generador de proyectos Backbone. Suponiendo que tenemos Node previamente instalado los pasos serían los siguientes:

```sh
npm install yo generator-backbone
```
Esto instalará Yeoman(yo) y su generador oficial de proyectos Backbone.

Ahora para generar un proyecto MVC simplemente le decimos a Yeoman que tipo de scaffolding queremos:

```sh
yo backbone:all
```
Algunos generadores tendremos que elegir ciertas opciones, en el caso de backbone el generador nos dará la posibilidad de elegir que librerias queremos usar para estilos y si (requerimos de "require")(jeje)

 ![yo backbone](http://i.imgur.com/PQ4MMU9.png) 

Y listo! después de todo esto podemos iniciar nuestro desarrollo sabiendo que 1, no comenzamos desde cero y 2, estaremos usando las convenciones y mejores práticas en backbone.

El proceso es muy similar para apps en express js, flux, MEAN etc. Por eso el uso de generadores es muy últil cuando comenzamos un nuevo proyecto.

**Comment by Sparragus** [comment]
En serio. Está plática hay que darla. Yo siempre hago mis proyectos usando snippets de código que tengo guardado:

"touch index.js server.js .eslint .babelrc webpack.config.js ..."
"mkdir client server models ..."

y entonces empiezo a poner más snippets de código dentro de cada archivo.

Hacer eso está súper culero.

@unRob, dude, yo creo que esto va a volarle la cabeza a muchos de la comunidad y va aumentar la productividad de todos. :D Se ve muy bien el tema. @everyone Qué dicen?

**Comment by unRob** [comment]
El tema nos pareció muy interesante y nos gustaria tenerte en un futuro evento, pero olvidé tomar en cuenta que es el aniversario en septiembre y queramos enfocarnos a cosas de es6 y el presente y futuro del lenguaje.

Te pido una disculpa, me tarde en organizar los contenidos de este mes!

**Comment by betolink** [comment]
Va, les aviso la próxima que ande por el DF. Igual me doy una vuelta en el evento del 2.

**Comment by unRob** [comment]
Mark-to-sweep por inactividad. Este issue se cerrará en 30 días salvo que se alguien adopte la charla.
