### ISSUE TITLE
JS: la solución a todos nuestros problemas

### ISSUE THREAD

**Issue by jaimerodas** [javascriptmx/chelajs#19]
Le vengo manejando una plática en la que se critique el gigantesco número de cosas para las que JS se está usando, compararlo con otras ingenierías que han pasado por el mismo problema, enseñar como varias compañías grandes ya les cagó JS y las maneras que están proponiendo para reemplazarlo/quitarlo.

**Comment by unRob** [comment]
Me late esta idea, ¿comentarios, @jeduan @Siedrix?

**Comment by jeduan** [comment]
:+1:
