### ISSUE TITLE
Charla sobre jQuery y Js, ¿Cuando es preferible usar cada uno?

### ISSUE THREAD

**Issue by PhixelHD** [javascriptmx/chelajs#2]
Una charla sobre la libreria jQ y Js, ¿Cuando es preferible usar jQuery?, ¿Cuando deberiamos usar Js puro?, saludos.

**Comment by jeduan** [comment]
La darías tu?

**Comment by PhixelHD** [comment]
No =(, yo solo la propongo :P

**Comment by jeduan** [comment]
Ok, entonces esperemos que alguien la vea. Por qué tu no?

**Comment by omarsharim** [comment]
Venga, @PhixelHD anímese, es una buena charla

**Comment by pateketrueke** [comment]
> [You Might Not Need jQuery](http://youmightnotneedjquery.com/)

**Comment by MichelAyala** [comment]
Yo quiero dar la platica. ¿hay alguna guía o documentación sobre cómo estructurar las platicas?
1. Duración
2. Cantidad de diapositivas
3. Estilo
4. Formato del documento

**Comment by unRob** [comment]
Gracias @MichelAyala, ¿qué tienes en mente sobre la estructura de la plática?

**Comment by jeduan** [comment]
@MichelAyala esta es una guía de la que te puedes apoyar https://github.com/javascriptmx/speakers

**Comment by MichelAyala** [comment]
@unRob Quiero hablar de porque y como surgió jQuery, como fue creciendo hasta ser la biblioteca de facto en JavaScript y sobre la nueva funcionalidad de JavaScript (querySelector por ejemplo).

**Comment by Sparragus** [comment]
@MichelAyala Creo que han estado saliendo varias libraries o frameworks que
fuertemente retan a jQuery como la biblioteca de facto en JS. Como piensas
atender ese tema? De hecho, la popularidad de jQuery ha estado disminuyendo
mucho. Considera React, por dar un ejemplo. Que crees?


Richard Kaufman

2015-10-14 18:44 GMT-05:00 Michel <notifications@github.com>:

**Comment by MichelAyala** [comment]
@Sparragus React es bueno, pero no todos hacemos cosas con el. Pero todos (o casi todos) hemos hecho cosas con jQuery.

Quiero hablar de porque surge jQuery en el 2005 (el API del DOM era un desmadre), como crece y como eventualmente muchas de las cosas con las que innovó se volvieron un estándar.

Web Components es una evolución (hasta cierto punto) de jQuery UI, los «queries» para hacer DOM scripting como '#container a.link', AJAX, Promesas, etc.

**Comment by Sparragus** [comment]
Tienes un punto con que no todos vamos a usar React, y mucho menos usarlo
tanto como se usaba jQuery. Mira, se me ocurre lo siguiente (quizas es lo
que quisiste decir desde un principio y yo no entendí):

1. Una plática de jQuery se me hace como algo del pasado. Por las mismas
razones que expones: el api del DOM antes era un desmadre, y jQuery nos
hacía la vida fácil. Por esa razón enfocarnos en jQuery se me hace un tema
anticuado.

2. Si estaría cool una plática sobre como abandonar jQuery a favor de lo
que ya nos ofrece ES6 y el API actual del DOM.

Que te parece eso, @MichelAyala? Que piensan los demás?

Richard Kaufman

2015-10-15 8:47 GMT-05:00 Michel <notifications@github.com>:

**Comment by JairAviles** [comment]
+1 al comentario anterior de @Sparragus

**Comment by MichelAyala** [comment]
@Sparragus pues eso era precisamente de lo que quiero hablar, quizá no me di a entender. La charla irá enfocada ne que hoy por hoy ya no necesitamos jQuery.

**Comment by pateketrueke** [comment]
Yo no entendí el punto de querer comparar React contra jQuery, más allá de que jQuery sea anticuado nada que ver un _toolkit_ de uso general a una librería especializada. :beers: 

Además igual no entiedo el _approach_ de cara a ES6, digo, jQuery resolvía principalmente temas específicos en el _browser_ y poco tiene que ver con el lenguaje per-se.

Lo único en lo que me concentraría, o bien, me gustaría ver son temas que sí tienen que ver con los navegadores: la API del DOM en específico ha evolucionado como para no depender más de jQuery.

Igual jQuery ofrece/ofrecía métodos de utilidad general que podemos encontrar de manera nativa en ES5 o librerías extras: sería bueno tener un compendio de dichas alternativas.

Es decir, no por usar ES6 ya resolvimos todo, y no por dejar de usar jQuery ya tenemos el día resuelto.

No es tan trivial: sobre todo en empresas grandes donde aún tenemos cosas _legacy_ como estas, pensar en el futuro suena romántico y no aplica a corto plazo el dejar de usar jQuery en todos los aspectos.

Yo no defiendo jQuery pero su utilidad sigue dando de que hablar.

**Comment by MichelAyala** [comment]
@pateketrueke bueno, es que nos pusimos a divagar.

**Comment by Sparragus** [comment]
@pateketrueke Ah dude. Todos tus puntos son válidos y coherentes. 

Mi comparación con React es rara (lo admito) pero es por que he visto como mucha gente sigue haciendo toda su app front-end con jQuery (solamente) cuando hay mejores herramientas. Y con ES6 por que hay features que vienen nativos (Promises como menciona @MichelAyala). Quizas hice mucho cherry picking y fui injusto.  Sobre código legacy, pues, no es trivial pero se va a volver un technical debt por ser legacy.

De todas formas, creo que vamos en la dirección correcta de aterrizar el tema de esta plática. 

Gracias por tus comentarios.

**Comment by unRob** [comment]
Al parecer tocaste un nervio @MichelAyala!

Me parece fenomenal la discusión al respecto, y creo justo por esto puede terminar siendo una plática increíble. Los puntos que toca @Sparragus me parecen esenciales, creo que habla de como jQuery no se entiende como la herramienta de manipulación del DOM, sino como _la herramienta_ por default de muchos devs tanto ocasionales como nuevos al ecosistema. Entiendo como React se podría convertir en algo así (a diferencia de algo como underscore o lodash, aún con un overlap mas amplio).

La idea detrás de plantear estas aparentes tangentes es aportar algo sobre la discusión que ya todos hemos leído en blogposts. jQuery ha sido una herramienta fundamental en la evolución de los programadores, lenguaje y runtimes; del mismo modo el tren del _virtual DOM_ es muy interesante, pues quien quita y nos cambia radicalmente lo que alguna vez fue el event binding y dom traversing como lo conocemos. 

Además, creo que el punto sobre legacy es muy importante para este tema, como menciona @pateketrueke; En los últimos 3 eventos hemos reiterado este asunto, no todos usamos navegadores de hace dos días, y es aquí dónde jQuery brilla.

En fin, @MichelAyala creo que ya tienes un buen de material para esta plática, a @Sparragus y a mi nos gustaría ver sobre estos comentarios un outline [mas extenso](https://github.com/javascriptmx/chelajs/issues/14), en especial por los sentimientos y attachment que todoas tenemos/tuvimos por jQuery.  

Por ejemplo, yo tengo los siguientes sentimientos sobre la discusión de este thread, y no me los guardo porqué ñoño y _somebody is wrong on the internet_:

- jQuery no creo el querying que ahora existe en el Selector API, pero definitivamente fue una pieza clave en su adopción. La notación sale de CSS, el uso de [cssQuery](http://dean.edwards.name/my/cssQuery/). Luego, yo tampoco usaría xPath.
- Me agrada el approach hacia estándares influenciados: recuerden que ES no es todo, también tenemos lo que engloba el buzzword de "HTML5"
- jQuery si tiene que ver con el lenguaje: `jQuery.forEach`, `jQuery.extend`, y `Deferred/jQuery.when` son algunos ejemplos de cosas que se modificaron en el lenguaje. La influencia chance no está documentada, pero _it sure feels like it_ :stuck_out_tongue_winking_eye:

**Comment by Sparragus** [comment]
@MichelAyala ¿Lograste hacer el outline?

**Comment by MichelAyala** [comment]
@Sparragus sí, hay mucho de donde escoger.

**Comment by Sparragus** [comment]
Nos las compartes acá?

**Comment by Sparragus** [comment]
@MichelAyala Si tienes el outline, no los compartes acá? Así podemos ver si te acomodamos en el ChelaJS :)

**Comment by MichelAyala** [comment]
@Sparragus ¿cuándo es el siguiente meetup?

**Comment by unRob** [comment]
El miércoles 4 de Noviembre; nos gustaría considerar para la que sigue, el miércoles 2 de Diciembre. Estaría buenazo leer tu outline para poderla ir agendando.

**Comment by MichelAyala** [comment]
@unRob dame una hora.

**Comment by MichelAyala** [comment]
# Boceto.
# JavaScript vs Jquery
## *(Or you might not need jQuery)*
---
# PART I
### (Historycal Context)
Back in 2005: web APIS were a mess!

- DOM Scripting
```js
// Wat?
getElementById('foo');
getElementsByClassName('bar');
getElementsByTagName('baz');
```
A lot of functions, why? Because W3C
No complex queries.

- AJAX
```js
// Standard Way
var xhr = new XMLHttpRequest();

// EI Way
var xhrvariable = new ActiveXObject("Microsoft.XMLHTTP");
```

Two different apps, why? Because IE.

- Animations

```js
// Fade-in-like
document
	.getElementById('#button')
	.addEventListener('click', function () {
		document
			.getElementById('#animation')
			.style
			.display = 'block';
	}
);
```
Complex code, why? Because 2005

# PART II
### You need jQuery

- DOM Scripting
Cross Browser Support.
Old Browser Support.
Complex queries.

```js
var foo = $('#foo');
var bar = $('.bar');
var baz_anchors = $('.baz a');
```

- AJAX

Cross Browser Support.
Old Browser Support.
JSON support.

```js
$.get('some_url.html');
$.post('ajax/register.php');
$.json('ajax/user_data.json');
```

- Animations  

```js
// Some element
$('#button').on('click', function () {
	$('#animation').fadeIn();
);
```

#### Extra stuff

- Promises
	- Own standard
- jQuery Mobile
	- Another library, why? Because yes.
- jQuery UI
	- Another one.

# PART III
### You might not need jQuery

- DOM Scripting

Complex queries.
Standard function.
Cross-browser support (soon)

Why? Because f*ck you W3C!

```js
// querySelector Babe!
var foo = document.querySelector('#foo');
var bar = document.querySelector('.bar');
var baz_anchors = document.querySelector('.baz a');
```

- AJAX

No more IE standard.
Write Once, Run Everywhere.

```js
var xhr = new XMLHttpRequest();
```

- Animations

Wait, wat? NO!
Use f*ckin' keyframes!

- Promises

Promises/A+ standard.  
Node supports it.

```js
// Avoid OOP in JavaScript... please!
var p = new Promise();
```

- Mobile support?

DOM Events support.
Hundreds of  libraries.

- UI?

Custom Elements.
Web Components.
Use libraries (i.e Polymer, x-tag).

**Comment by Sparragus** [comment]
Puedes acomodar todo esto en 20 minutos?

On Thursday, October 29, 2015, Michel <notifications@github.com> wrote:

> Boceto. JavaScript vs Jquery *(Or you might not need jQuery)*
> ------------------------------
> PART I (Historycal Context)
>
> Back in 2005: web APIS were a mess!
>
>    - DOM Scripting
>
> // Wat?getElementById('foo');
> getElementsByClassName('bar');getElementsByTagName('baz');
>
> A lot of functions, why? Because W3C
> No complex queries.
>
>    - AJAX
>
> // Standard Wayvar xhr = new XMLHttpRequest();
> // EI Wayvar xhrvariable = new ActiveXObject("Microsoft.XMLHTTP");
>
> Two different apps, why? Because IE.
>
>    - Animations
>
> // Fade-in-likedocument
>     .getElementById('#button')
>     .addEventListener('click', function () {
>         document
>             .getElementById('#animation')
>             .style
>             .display = 'block';
>     }
> );
>
> Complex code, why? Because 2005
> PART II You need jQuery
>
>    - DOM Scripting Cross Browser Support. Old Browser Support. Complex
>    queries.
>
> var foo = $('#foo');var bar = $('.bar');var baz_anchors = $('.baz a');
>
>
>    - AJAX
>
> Cross Browser Support.
> Old Browser Support.
> JSON support.
>
> $.get('some_url.html');
> $.post('ajax/register.php');
> $.json('ajax/user_data.json');
>
>
>    - Animations
>
> // Some element
> $('#button').on('click', function () {
>     $('#animation').fadeIn();
> );
>
> Extra stuff
>
>    - Promises
>       - Own standard
>    - jQuery Mobile
>       - Another library, why? Because yes.
>    - jQuery UI
>       - Another one.
>
> PART III You might not need jQuery
>
>    - DOM Scripting
>
> Complex queries.
> Standard function.
> Cross-browser support (soon)
>
> Why? Because f*ck you W3C!
>
> // querySelector Babe!var foo = document.querySelector('#foo');var bar = document.querySelector('.bar');var baz_anchors = document.querySelector('.baz a');
>
>
>    - AJAX
>
> No more IE standard.
> Write Once, Run Everywhere.
>
> var xhr = new XMLHttpRequest();
>
>
>    - Animations
>
> Wait, wat? NO!
> Use f*ckin' keyframes!
>
>    - Promises
>
> Promises/A+ standard.
>
> Node supports it.
>
> // Avoid OOP in JavaScript... please!var p = new Promise();
>
>
>    - Mobile support?
>
> DOM Events support.
> Hundreds of libraries.
>
>    - UI?
>
> Custom Elements.
> Web Components.
> Use libraries (i.e Polymer, x-tag).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/2#issuecomment-152396829>.
>


-- 
Richard Kaufman

**Comment by MichelAyala** [comment]
Supongo que sí.

**Comment by unRob** [comment]
Mark-to-sweep por inactividad. Este issue se cerrará en 30 días salvo que se alguien adopte la charla.

**Comment by Sparragus** [comment]
Cerrando por inactividad.
