### ISSUE TITLE
CopilotJs - Angular/React/Flux

### ISSUE THREAD

**Issue by alfruiz86** [javascriptmx/chelajs#20]
Este es un framework que estamos desarrollando in-house para crear una arquitectura responsiva. Que seria la función de un "Responsive Design" con un "Apative Web Design".

Logrando hacer que las UI genere una optima UX para los usuarios en diversos dispositivos y en un solo encapsula-miento de código.

**Comment by unRob** [comment]
Gracias por tu propuesta Alfonso, pero no me queda muy claro de qué se trata la plática, ¿estamos hablando de que nos cuentes sobre lo que aprendiste de tu framework? ¿Una invitación a usarlo? ¿Una comparación con los frameworks y patrones mencionados en el título? Si puedes ser un poco mas conciso, creo que podríamos trabajar sobre esta propuesta!

**Comment by unRob** [comment]
Mark-to-sweep por inactividad. Este issue se cerrará en 30 días salvo que se presente un outline para el mismo.
