### ISSUE TITLE
<canvas>

### ISSUE THREAD

**Issue by Sparragus** [javascriptmx/chelajs#22]
Una plática sobre usar `<canvas>`. Quizas usando p5js o d3 o cualquier otro framework.

¿Quién se anima a darla?

**Comment by unRob** [comment]
¿Qué en particular? Creo que está muy ambigua la propuesta, pero me late que se levanten este tipo de discusiones, chance así podemos ver qué les interesaría escuchar en próximos eventos.

**Comment by Sparragus** [comment]
La sugerí por que ayer Chrome corto su relación con Flash. <canvas> es una
de las opciones que Google quiere que empecemos a implementar.

No puse un propuesta específica sobre la mesa por que no voy a dar la
plática yo. Pero por ejemplo. quizas alguien ya hace un tiempi había hecho
la transición de Flash a HTML5 y nos puede compartir algo.

Mientras tanto, let's wait :D

Richard Kaufman

2015-09-03 2:30 GMT-05:00 Roberto Hidalgo <notifications@github.com>:

**Comment by marulango** [comment]
Para el de noviembre chance me puedo aventar esta yo

**Comment by unRob** [comment]
Me late @marulango, ¿me ayudas con el outline de la plática? ¿Te aventarías a echártela en octubre?

**Comment by marulango** [comment]
So~


Usando p5js, que es el port de processing (java) a javascript, se pueden hacer muchas clases de visualizaciones. Prácticamente todo el dato que se pueda convertir a binario, se puede graficar con esto. (Y eso es, pues, pretty much everything)

Ahora, se pueden hacer ejemplos super fáciles de cómo manipular pixeles y de como usar el audio/cámara/cualquier-cosa-que-genere-datos para dar instrucciones a los pixeles en base a su información en tiempo real. 
Dentro del maravilloso elemento de canvas. 
Para cuando queramos no usar el animal extraño que es SVG.

**Comment by Sparragus** [comment]
Suena súper cool. Quizas entonces la plática, más allá de ser de canvas, puede ser específica de p5js. ¿Qué creen?

**Comment by marulango** [comment]
Hmnnn…creo que estaría mejor. 
O podría ser un showcase de qué hacer con canvas que no sea la forma super dull que tiene para dibujar.
