### ISSUE TITLE
Tecnicas de debugging para JS

### ISSUE THREAD

**Issue by Siedrix** [javascriptmx/chelajs#23]
Una de las platicas mas pedidas es sobre como hacer debugging en javascript y las técnicas recomendadas.

**Comment by Sparragus** [comment]
Siii. Este es muy buen tema.

+1

Richard Kaufman

2015-09-15 13:21 GMT-05:00 Siedrix <notifications@github.com>:

**Comment by unRob** [comment]
Mark-to-sweep por inactividad. Este issue se cerrará en 30 días salvo que se presente un outline para el mismo.

**Comment by devrchancay** [comment]
¿Todo esto es para mexico? puede ser online. solo que la cerveza seria muy dificil compartirlo.

**Comment by unRob** [comment]
Es correcto, los eventos son en la Ciudad de México @devrchancay. Si quieres puedes ver el evento en vivo por [youtube](https://www.youtube.com/channel/UCsmWJI_UTYDbggvYoOATcIQ), y si quieres adoptar la plática podemos hablar de la logística en [Slack](http://chat.javascriptmx.com).
