### ISSUE TITLE
Del odio al amor con JS

### ISSUE THREAD

**Issue by sixviv** [javascriptmx/chelajs#24]
Ningun lenguaje es perfecto, y Javascript no es la excepción. Hay muchas personsas que dicen cosas terribles, y por la experiencia que había tenido con el, lo despreciaba inmediatemente. Sin embargo, últimamente ha estado resonando mucho, y despertó mi curiosodad, tanto se convirtió en mi pasatiempo favorito. 

En esta plática quiero resaltar los atributos que hicieron que lo empezara amar.

**Comment by unRob** [comment]
Me late la idea, ¿cómo que elementos te gustaría mostrar? Creo que también sería interesante ver los resultados que has obtenido a través de tu pasatiempo, ¿qué te parece?

**Comment by sixviv** [comment]
@unRob tengo dos en mente:
- El tamaño del core de JS
- La flexibildad que tiene JS, la cual te permite ser tan creativo como quieras
En base a esos dos, mostrar lo mucho que se puede hacer con pequeños ejemplos o bien con la aplicación que he estado haciendo como pasatiempo.

Cómo ves?

**Comment by Siedrix** [comment]
Que fechas estaras por el df?

**Comment by sixviv** [comment]
Para el meetup de Octubre podría andar por allá

**Comment by unRob** [comment]
Mark-to-sweep por inactividad. Este issue se cerrará en 30 días salvo que se alguien adopte la charla.

**Comment by Sparragus** [comment]
Cerrando por inactividad.
