### ISSUE TITLE
Electrificando la casa con node

### ISSUE THREAD

**Issue by mruba** [javascriptmx/chelajs#25]
Desde hace muchos años tenia en mente hacer domotica y no fue hasta hace algunos meses cuando me di cuenta que tenia todo lo necesario a mi alcance para hacerlo con un presupuesto pequeño y con la ayuda de Node y X10 ( un protocolo de comunicación que utiliza la red electrica como medio de transporte ), el proposito principal de esta platica es compartir el gran espectro tecnologico de uso que existe en Node y el alcance que tiene usar este lenguaje y por supuesto compartir mi historia.

**Comment by unRob** [comment]
Me late la idea de mostrar Node como un excelente **runtime** para quienes nos vamos interesando en IoT, pero creo que sería útil mencionar las ventajas sobre otros runtimes y herramientas, ¿cómo ves? Por otro lado, ¿qué ventajas/desventajas le encontraste a Javascript al hacer este proyecto? Creo que hablar del rol que juega el lenguaje le podría ayudar a quienes no le han jugado al hardware antes, ¿qué te parece?

**Comment by mruba** [comment]
Me parece bien, sobre las ventajas voy a quedar un poco corto por que solo he utilizado python para estas cosas pero puedo investigar, en cuanto a las ventajas y desventajas creo que vale mencionar que una de las cosas por la cual decidí usar Node es por la forma en la que se usan websockets por que quería actualizar el estado de los swiches en tiempo real en distintas plataformas y desventajas es que no hay muchas librerías para usar con cosas como Myo ó RPI que son los dispositivos que utilizo para controlar el API de la luz.

**Comment by unRob** [comment]
Me late, para qué evento te gustaría presentar esta plática?

**Comment by mruba** [comment]
La ultima vez que hablamos me comentaste que estabas planeando hacer una chelajs con sabor a hardware, creo que para ese evento estaria super a reserva de lo que tu me digas.

**Comment by unRob** [comment]
Sí, me gustaría armar uno, pero no hemos recibido propuestas al respecto. Estoy pensando armarla junto con #17 para armar un evento sobre ecosistema y tooling, posiblemente en noviembre, ¿cómo ves?

**Comment by unRob** [comment]
Vamos a irla preparando para Noviembre de una vez; Aprovecho para encomendarme a San @xiam para sacar otra plática de hardware o de [gopherjs](/gopherjs/gopherjs) _guiño, guiño_.

**Comment by mruba** [comment]
Excelente, entonces queda para noviembre, a ver si cuando tenga un draft de la presentación le hechas un ojo

**Comment by unRob** [comment]
Perdón, la :hankey:

**Comment by Sparragus** [comment]
Hey @mruba! Dude, me tope con este video. Quizas te sirva para la plática. Raquel Vélez es LA persona para lo que sea JS + Hardware. Checa la presentación :D https://www.youtube.com/watch?v=3v75aX5-gSA

Que de hecho, aprovecho para preguntar, como vas? Has logrado concentrar la plática en una de Javascript? (No quieres que la gente te vaya a tirar tomates! 😲     🍅💨👋😡) Tendrás algún outline de la plática?

**Comment by mruba** [comment]
@Sparragus gracias dude! lo estoy tomando en cuenta, espero poderles compartir un draft el dia de hoy para que lo chequen y me retroalimenten, saludos.
