### ISSUE TITLE
Node 4.0

### ISSUE THREAD

**Issue by jeduan** [javascriptmx/chelajs#26]
Todo mundo se queja de que en Javascript no sabemos usar Numeros y prueba de esto es la reciente muestra de que del 0.12 sigue el 4.0

Esta plática pretende demostrar que matemáticamente esta es una secuencia valida.

Ah y hablar de lo nuevo del runtime también.

**Comment by archr** [comment]
>Todo mundo se queda de que en Javascript no sabemos usar Numeros

🍺

**Comment by rogr** [comment]
Toda esa gente que decía que Node.js nunca tendría una versión 1.0 estable pues, tenian razón...
