### ISSUE TITLE
Generators, Co y Koa

### ISSUE THREAD

**Issue by Sparragus** [javascriptmx/chelajs#27]
*¿Por qué?*
  2. Yo escribo mis servers con Express. Koa está escrito por la misma gente que hizo Express. Por alguna razón se cambiaron a [Koa](http://koajs.com/). Estaría cool que alguien me explique que onda.
  3. Usar Koa implica usar [*generators*](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*). Pero los generators que yo conozco son los que se usan para hacer lazy loading del próximo número en la secuencia Fibonacci. Cuando veo los generatos como Koa los usa, no entiendo nada. Se ven súper 1337.
  4. Si entiendes Koa, creo que entiendes [Co](https://github.com/tj/co) también. Co tiene un tagline muy awesome que me hace sentir mal no conocerlo: *The ultimate generator based flow-control goodness for nodejs (supports thunks, promises, etc*. Whatever that means, yo quiero. Lo cual me lleva a mi último punto...
  5. Co y Koa están escritos por los dedos mágicos de [tj](https://github.com/tj). Y todos sabemos que tj es dios.
  6. Todos mis amigos lo usan. xD

¿Quién se atreve a explicar Generators, Co y Koa en 20 minutos?

**Comment by markotom** [comment]
+1

**Comment by rogr** [comment]
Yo puedo hacer esto, pero ¿para cuando seria?.

**Comment by Sparragus** [comment]
Al parecer para diciembre.

**Comment by rogr** [comment]
Cool, sí, prepararé un sketch esta semana, a ver si les late.

**Comment by Sparragus** [comment]
Wiiiiin! Dale dude. :D Nos avisas cuando tengas tu bosquejo.

Richard Kaufman

**Comment by cesarandreu** [comment]
FYI: [koa 2.0](https://github.com/koajs/koa/issues/533) breaks backwards compatibility, y es bien probable que para diciembre esté en la versión estable.

```js
// Async~
app.use(async (ctx, next) => {
  /* ... */
})

// Generator~
app.use(function * (ctx, next) {
  /* ... */
})
```

**Comment by Sparragus** [comment]
Hey @rogr! De verdad me gustaría agendarte para el próximo chelajs. Este tema esta súper trending. :D Creo que a todos nos va a interesar mucho. 

Tendras un outline de tu plática? Así lo revisamos y confirmamos tu plática.

**Comment by unRob** [comment]
@rogr Quihubo dude, ¿cómo ves presentar en diciembre?

**Comment by rogr** [comment]
@unRob perfecto. Ya le había confirmado a @jeduan.
De hecho ya estoy escribiendo el sketch de mi platica.

**Comment by rogr** [comment]
@Sparragus ¿Quieres que se enfoque mas en Koa o en Co? Es que estoy haciendo mi sketch y como que me oriente mas en Co y creo ya me debraye con Generators, Promises y Thunks.

**Comment by Sparragus** [comment]
Listo. Hacia Co está perfecto. :D

Quizas Koa lo puede presentar otra persona otro día. Lo que sí es que
quizas puedes hacer un mention al final.

Richard Kaufman

2015-11-25 12:57 GMT-06:00 Rogelio <notifications@github.com>:
