### ISSUE TITLE
Creando interfaces de usuario con Elm

### ISSUE THREAD

**Issue by MachinesAreUs** [javascriptmx/chelajs#28]
Elm es un lenguaje y plataforma que compila a javascript y corre en el navegador.
¿Por qué utilizar Elm en lugar de Javascript? Dos respuestas:
- Productividad
- Mantenibilidad.

Elm trae los beneficios de ser un lenguaje de programación funcional (productividad y expresividad) pero complementado con un sistema de tipos que, a diferencia de lenguajes como por ejemplo Java, no se interpone en tu camino pero sí te cuida de cometer muchos errores.

¿Cuántas veces no te has encontrado con un error que dice "undefined is not a function" y has tardado mucho tiempo en encontrar la causa original, ya que el error se pudo haber escondido entre varias llamadas? ¿Cuántas veces has querido refactorizar un proyecto pero el hecho de que en JS no hay herramientas que te ayuden a encontrar todas  las partes de código que hay que mover, hace que el proceso sea muy lento o propenso a errores?

Ese tipo de problemas son los que Elm apunta a solucionar.

**Comment by unRob** [comment]
Acabo de ver algo de Elm en [un video Elixirconf](https://www.youtube.com/watch?v=MgFDZx1LmOE) y me causo mucha curiosidad. Me late el tema, sobre todo si hablamos de la dualidad del lenguaje/runtime, y como Elm es una alternativa viable.

Hace poco hablamos de clojurescript, y creo que sería un buen refuerzo del tema funcional, pero me preocupa la complejidad del mismo, ¿Qué se te ocurre para hacerlo accesible a quienes hemos hecho poco FP?

**Comment by Sparragus** [comment]
+10

On Monday, October 19, 2015, Roberto Hidalgo <notifications@github.com>
wrote:

> Acabo de ver algo de Elm en un video Elixirconf
> <https://www.youtube.com/watch?v=MgFDZx1LmOE> y me causo mucha
> curiosidad. Me late el tema, sobre todo si hablamos de la dualidad del
> lenguaje/runtime, y como Elm es una alternativa viable.
>
> Hace poco hablamos de clojurescript, y creo que sería un buen refuerzo del
> tema funcional, pero me preocupa la complejidad del mismo, ¿Qué se te
> ocurre para hacerlo accesible a quienes hemos hecho poco FP?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/28#issuecomment-149350259>
> .
>


-- 
Richard Kaufman

**Comment by Sparragus** [comment]
Para elaborar más por qué me late el tema: redux esta súper inspirado por
elm.

On Monday, October 19, 2015, Agustín Ramos <notifications@github.com> wrote:

> Elm es un lenguaje y plataforma que compila a javascript y corre en el
> navegador.
> ¿Por qué utilizar Elm en lugar de Javascript? Dos respuestas:
>
>    - Productividad
>    - Mantenibilidad.
>
> Elm trae los beneficios de ser un lenguaje de programación funcional
> (productividad y expresividad) pero complementado con un sistema de tipos
> que, a diferencia de lenguajes como por ejemplo Java, no se interpone en tu
> camino pero sí te cuida de cometer muchos errores.
>
> ¿Cuántas veces no te has encontrado con un error que dice "undefined is
> not a function" y has tardado mucho tiempo en encontrar la causa original,
> ya que el error se pudo haber escondido entre varias llamadas? ¿Cuántas
> veces has querido refactorizar un proyecto pero el hecho de que en JS no
> hay herramientas que te ayuden a encontrar todas las partes de código que
> hay que mover, hace que el proceso sea muy lento o propenso a errores?
>
> Ese tipo de problemas son los que Elm apunta a solucionar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/28>.
>


-- 
Richard Kaufman

**Comment by MachinesAreUs** [comment]
@unRob De hecho he estado pensando en eso, ¿cómo hacer que los desarrolladores de JS no se sientan intimidados por el tema de programación funcional y se atrevan a probar Elm?

La respuesta es simple: prácticamente omitirlo. Es decir, omitiría introducir nombres de conceptos que puedan ser una barrera a escuchar de qué se trata.

En JS ya están acostumbrados a andar pasando funciones como parámetros y valores de retorno. En ese sentido ya vamos de gane. Uno detalle de la forma que quiero presentarlo es poniendo snippets de código en JS y luego su equivalente en Elm. Ya con esos primeros ejemplos poder mostrar cosas más elaboradas como una aplicación MVC, unas animaciones y un videojuego.

**Comment by jeduan** [comment]
+1 y nada más agregar que este repo / guía estuvo de #1 en github hace un par de meses y fue cómo su servidor le entendió un poco más a fp, el sistema de tipos y supo de repos como lodash-fp. Nunca hemos sugerido que los asistentes hagan nada antes/después de un evento pero podría ser interesante considerarlo. 

https://github.com/MostlyAdequate/mostly-adequate-guide

**Comment by MachinesAreUs** [comment]
"JavaScript will be our means of learning a paradigm, where you apply it is
up to you. Luckily, the interfaces are mathematical and, as such,
ubiquitous. You'll find yourself at home with swiftz, scalaz, haskell,
purescript, and other mathematically inclined environments."

2015-10-19 23:01 GMT-05:00 Jeduan Cornejo <notifications@github.com>:

> +1 y nada más agregar que este repo / guía estuvo de #1 en github hace un
> par de meses y fue cómo su servidor le entendió un poco más a fp, el
> sistema de tipos y supo de repos como lodash-fp. Nunca hemos sugerido que
> los asistentes hagan nada antes/después de un evento pero podría ser
> interesante considerarlo.
>
> https://github.com/MostlyAdequate/mostly-adequate-guide
>
> > On 19/10/2015, at 4:22 p.m., Agustín Ramos <notifications@github.com>
> wrote:
> >
> > @unRob De hecho he estado pensando en eso, ¿cómo hacer que los
> desarrolladores de JS no se sientan intimidados por el tema de programación
> funcional y se atrevan a probar Elm?
> >
> > La respuesta es simple: prácticamente omitirlo. Es decir, omitiría
> introducir nombres de conceptos que puedan ser una barrera a escuchar de
> qué se trata.
> >
> > En JS ya están acostumbrados a andar pasando funciones como parámetros y
> valores de retorno. En ese sentido ya vamos de gane. Uno detalle de la
> forma que quiero presentarlo es poniendo snippets de código en JS y luego
> su equivalente en Elm. Ya con esos primeros ejemplos poder mostrar cosas
> más elaboradas como una aplicación MVC, unas animaciones y un videojuego.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/28#issuecomment-149425257>
> .
>



-- 
"The opposite of a true statement is a false statement, but the opposite of
a profound truth is usually another profound truth."
Neils Bohr (1885 - 1962)

**Comment by Sparragus** [comment]
@MachinesAreUs ¿Nos puedes preparar un outline de lo que sería tu plática? Algo más delineado y con temas/subtemas más específicos. Con eso le podemos dar una revisión más al contenido y conseguirle fecha a la plática. :)

**Comment by MachinesAreUs** [comment]
Outline:

- ¿Por qué es interesante Elm para programadores Javascript?
- Introducción al lenguaje para programadores de Javascript.
- Creando aplicaciones web con "The Elm Architecture"
- El core de Elm: señales.
- Ejemplos divertidos de gráficos con Elm.
- Time travel debugging con Elm.
- Introduciendo Elm dentro de una aplicación Javascript.
- Comentarios sobre los beneficios de Elm.

**Comment by Sparragus** [comment]
Suena como una plática bastante epic. :D Ya quiero!

Crees que puedes condensar todo eso en 20 minutos?

Richard Kaufman

2015-10-20 11:56 GMT-05:00 Agustín Ramos <notifications@github.com>:

**Comment by MachinesAreUs** [comment]
jajajaja.. no, en 20 ni de chiste =/
La verdad se me complicaría mucho transmitir la onda de Elm en menos de 50 min.

**Comment by hiphoox** [comment]
Denle al menos 40 minutos para que el tema valga la pena

**Comment by unRob** [comment]
Buscamos que las charlas siembren la suficiente curiosidad en los asistentes para que se animen a investigar por su cuenta, exponernos a herramientas nuevas y escuchar la experiencia de quienes las han usado. En este sentido, creo que un acercamiento mucho mas superficial a Elm podría condensarse en 20 minutos.

Por otro lado, me gustaría explorar la posibilidad de hacer "series" de charlas, apoyándonos en la grabación de cada evento para quienes se pierdan de alguna sesión. Del mismo modo, el material debe de condensarse a 20 minutos, pero podría ser explicado a lo largo de 3 sesiones.

¿Te late alguna de las dos ideas @MachinesAreUs?

**Comment by MachinesAreUs** [comment]
Yo creo que lo de 3 sesiones puede funcionar.

2015-10-29 17:05 GMT-06:00 Roberto Hidalgo <notifications@github.com>:

> Buscamos que las charlas siembren la suficiente curiosidad en los
> asistentes para que se animen a investigar por su cuenta, exponernos a
> herramientas nuevas y escuchar la experiencia de quienes las han usado. En
> este sentido, creo que un acercamiento mucho mas superficial a Elm podría
> condensarse en 20 minutos.
>
> Por otro lado, me gustaría explorar la posibilidad de hacer "series" de
> charlas, apoyándonos en la grabación de cada evento para quienes se pierdan
> de alguna sesión. Del mismo modo, el material debe de condensarse a 20
> minutos, pero podría ser explicado a lo largo de 3 sesiones.
>
> ¿Te late alguna de las dos ideas @MachinesAreUs
> <https://github.com/MachinesAreUs>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/28#issuecomment-152352559>
> .
>



-- 
"The opposite of a true statement is a false statement, but the opposite of
a profound truth is usually another profound truth."
Neils Bohr (1885 - 1962)

**Comment by pateketrueke** [comment]
+1

**Comment by hiphoox** [comment]
Me parece bien también lo de las 3 sesiones.

**Comment by unRob** [comment]
¿Sí se armará esta charla para diciembre? ¿Quién de los dos se la quiere aventar?

**Comment by hiphoox** [comment]
Yo con todo gusto puedo.

**Comment by unRob** [comment]
¡Vientos! ¿Nos echas la mano con un outline de lo que cubriría la primer sesión?

**Comment by hiphoox** [comment]
Si, solamente no se si Agustin también quiera dar la charla.

Norberto

**Comment by MachinesAreUs** [comment]
De que quiero, sí quiero :smile: 
Pero como será en martes y ya estaré reubicado en la tierra de las tortas ahogadas, no podré :disappointed: Adelante @hiphoox !

**Comment by hiphoox** [comment]
Ok, entonces preparo el outline y te lo mando

**Comment by hiphoox** [comment]
Primera sesión

Introducción a Elm
	Funciones
	Módulos
	Generando HTML
Arquitectura de una web app en Elm

**Comment by hiphoox** [comment]
¿Para que fecha es el evento?

Norberto

**Comment by Sparragus** [comment]
El 2 de diciembre

Richard Kaufman

2015-11-23 17:35 GMT-06:00 Norberto Ortigoza <notifications@github.com>:

> ¿Para que fecha es el evento?
>
> Norberto
>
> > On Nov 20, 2015, at 10:27 AM, Norberto Ortigoza <

**Comment by hiphoox** [comment]
Ok, ahí nos vemos.


Norberto

**Comment by Sparragus** [comment]
Hola @hiphoox!

Qué te parece continuar con la serie de Elm en el Chelajs de febrero? Nos preparas un outline para esa sesión? :D

**Comment by Sparragus** [comment]
@hiphoox Has considerado dar la plática para Chelajs de febrero?

**Comment by hiphoox** [comment]
Hola,

¿Para que fecha sería?

Norberto

**Comment by Sparragus** [comment]
El miércoles 3 de febrero.

**Comment by hiphoox** [comment]
No, ahora si no puedo para esa fecha. 
Mejor por favor anotarme para la de marzo.

Norberto

**Comment by Sparragus** [comment]
Bueno. Gracias! Te avisamos :)
