### ISSUE TITLE
Por qué 0.1 + 0.2 no es 0.3 en JavaScript 

### ISSUE THREAD

**Issue by jeduan** [javascriptmx/chelajs#3]
Propuesta para Omar Sharim

**Comment by jeduan** [comment]
@omarsharim

**Comment by omarsharim** [comment]
¡Perfecto!

**Comment by Carlangueitor** [comment]
Pero esto pasa en todos los lenguajes que usan flotantes IEEE 754, digo por el titulo que suena excluyente.

**Comment by omarsharim** [comment]
La platica la quiero centrar en Javascript, no solo en IEEE 754 y ver de que forma se pueden resolver estos problemas y de que forma ECMAScript maneja Numeros.

**Comment by jeduan** [comment]
Si, de hecho lo de JavaScipt fue de mi cosecha, el pitch de Omar es de todos los lenguajes IEEE 754

**Comment by Carlangueitor** [comment]
Cool :+1:

**Comment by razpeitia** [comment]
What Every Computer Scientist Should Know About Floating-Point Arithmetic
http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by pateketrueke** [comment]
> Si, de hecho lo de JavaScipt fue de mi cosecha, el pitch de Omar es de todos los lenguajes IEEE 754

:beers:

**Comment by SergioMartinezP** [comment]
+1 por que si es un tema, en especial en aplicaciones financieras

**Comment by Siedrix** [comment]
Pero tenemo Number.EPSILON en ES6  http://www.2ality.com/2015/04/numbers-math-es6.html?utm_source=javascriptweekly&utm_medium=email&m=1

```
    function epsEqu(x, y) {
        return Math.abs(x - y) < Number.EPSILON;
    }
    console.log(epsEqu(0.1+0.2, 0.3)); // true
```

**Comment by rogr** [comment]
![Imgur](http://i.imgur.com/DMYOWyH.png)

**Comment by jeduan** [comment]
Hola @osharim te gustaría preparar esta plática para el ChelaJS de Agosto que sería tentativamente el 5 de Agosto?

**Comment by osharim** [comment]
¡Perfecto! que se cocine la charla para Agosto
