### ISSUE TITLE
React vs AngularJS: un benchmark hecho por alguien nuevo a ambos frameworks

### ISSUE THREAD

**Issue by rodowi** [javascriptmx/chelajs#30]
![fight](http://www.diariodocentrodomundo.com.br/wp-content/uploads/2013/08/mortal-kombat.png)

## de qué
- de mi experiencia aprendiendo y comparando React y AngularJS
- para ejemplificar la experiencia, usaré un proyecto propio (no un TODO app!)
- le dedicaré 5 minutos a cada framework
- y 5 minutos a las diferencias

## por que´
- porque creo que una habilidad importante es saber evaluar y comparar frameworks y tecnología, y no dejarse llevar por los buzzwords

**Comment by unRob** [comment]
Rod, como te platiqué estamos buscando armar un evento de front-end, y ya lo empezamos a cocinar. ¿En qué mes me dijiste que no vas a estar disponible?

**Comment by unRob** [comment]
Esto estaría de huevos con #14 y #34

**Comment by Sparragus** [comment]
Yes! Si podemos hacer estas tres pláticas en un evento sería muy épico. :D

Richard Kaufman

2015-11-25 0:31 GMT-06:00 Roberto Hidalgo <notifications@github.com>:

**Comment by rodowi** [comment]
@unRob: 

> ¿En qué mes me dijiste que no vas a estar disponible?

```javascript
undefined
```

**Comment by rodowi** [comment]
Dado que `undefined`, estaría cool que alguien más se apuntara a dar esta plática.

**Comment by unRob** [comment]
¿Se aclaró el panorama o prefieres que etiquetemos la plática como "en búsqueda de ponente"?

**Comment by jeduan** [comment]
Dado el último párrafo de http://rodowi.github.io/refactor/articulo/2015/12/08/cambios.html voy a suponer a menos que el bueno @rodowi me contradiga que lo segundo.

**Comment by rodowi** [comment]
@unRob Sugiero "en búsqueda de ponente"

**Comment by Sparragus** [comment]
Mark-to-sweet por inactividad. En 30 días se cerrará este issue a menos que alguien retome el tema.
