### ISSUE TITLE
Experimientos con Web MIDI API y Web Audio API

### ISSUE THREAD

**Issue by orlando** [javascriptmx/chelajs#31]
## Web MIDI API + Web Audio API + Novation Launchpad = WebLaunchpad

La idea de la platica es explorar estos 2 APIs (Web AUDIO y Web MIDI), combinarlos con un controlador MIDI, y hacer un engine de _sampleo_, en el cual tu puedes elegir el set de sonidos ("sample packs") que quieras y sirva como base para hacer otros experimentos.

## Background

Di una presentación rapida sobre esto en el Chilango Rails ([slides](https://speakerdeck.com/orlando/web-launchpad) y [codigo](https://github.com/orlando/web-launchpad)). La idea es expandir un poco mas el tema y hacer musica live usando el browser y un controlador MIDI

## Content

1. Web Audio API
  * Para que sirve y que podemos hacer con el
  * Soporte
  * API
  * Como se uso en el demo
2. Web MIDI API
  * Para que sirve y que podemos hacer con el
  * Soporte
  * API
  * Como se uso en el demo
3. Novation Launchpad
  * Como se comunica con el Web MIDI API
  * API
  * Como se uso en el demo
4. Demo
5. QA

## Demo

El demo quiero que sea algo más extenso que [código](https://github.com/orlando/web-launchpad). La idea es agregar los siguientes features

1. Poder cambiar/agregar samples
2. Visualizar los eventos del controlador (botones que se presionan)
3. Poder grabar un session (nice to have)

Del resto son los básicos, como conectar el controlador, tocar un sample e iluminar el controlador.

**Comment by Sparragus** [comment]
Dude, me encanta el tema. Me gusta mucho que continuemos con pláticas de bibliotecas/APIs que sean para uso creativo, como la https://github.com/javascriptmx/chelajs/issues/22 de p5.js.

Vi tu presentación, pero no vi ejemplos de código (sí los vi en el github). Me gustaría que nos enseñaras un poco de código durante la plática y algunos demos. Como ves?

**Comment by orlando** [comment]
@Sparragus Sure, de hecho se me hizo raro que pregunten por el código (lo explique luego en vivo cuando di la presentación en Chilango Rails), pero totalmente dispuesto a explicar el código en la misma platica. Igual el demo que haga va a estar disponible en un repo en Github

**Comment by Sparragus** [comment]
@orlando Ah dude. No lo decía en el sentido de que expongas toda la aplicación y nos las expliques, si no más bien para dar contexto al API. Se entiende lo que quiero decir? Me refiero a snippets de código.

**Comment by orlando** [comment]
@Sparragus ah sure, perfecto, that works.

**Comment by Sparragus** [comment]
@orlando Para ser uniforme con todas las propuestas, y para tener claro el tema, nos puedes preparar un outline de lo que sería tu plática. No tienes que ser detallado, si no que general. Ten en cuenta que la plática no debe durar más de 20 minutos.

**Comment by orlando** [comment]
@Sparragus cool, hoy en la noche o mañana temprano lo hago y updateo el primer mensage.

Thanks!

**Comment by Sparragus** [comment]
Awesome! Gracias a ti :D

Richard Kaufman

On Mon, Nov 9, 2015 at 5:24 PM, Orlando Del Aguila <notifications@github.com

**Comment by Sparragus** [comment]
Dude, epic. Tu plática está aceptada. Congrats! :D

El próximo ChelaJS es el 2 de diciembre a las 7:30pm. Como quiera, antes de eso te estaremos escribiendo al email que aparece en tu github con más detalles.

Nos vemos pronto! :D

**Comment by orlando** [comment]
@Sparragus Awesome, nos vemos pronto y gracias por el quick feedback loop.

**Comment by unRob** [comment]
El próximo evento será el miércoles 2 de Diciembre, ¿te animas a presentar entonces @orlando? Aunque ya escuché tu charla en ChilangoRails, me gustaría coordinar un hangout para empaparnos un poquito mas del tema, ¿cuándo crees tener el material listo para repasar brevemente tu charla?

**Comment by orlando** [comment]
@unRob creo que en un par de semanas, vamos a decir que para el Lunes 23 de Noviembre para tener 2 fines libres para trabajarlo.

Y si, para el 2 de Diciembre sirve perfecto.
