### ISSUE TITLE
React: flux vs redux

### ISSUE THREAD

**Issue by oscaroceguera** [javascriptmx/chelajs#33]
Que es mas factible en este momento usar para desarrollar un a app en React.js la arquitectura Flux o Redux

**Comment by ErasmoLeon** [comment]
Hola, me gustaría dar esta plática.

### De qué:

1. Conociendo flux.
2. Principios redux.
3. Conceptos básicos redux y diferencias sustanciales respecto flux.
4. 10 min para revisar código, una aplicación simple con redux.

### Por qué:

Hoy en día existen muchas implementaciones de flux, 
es importante conocer alternativas y entre más simple mejor.

**Comment by unRob** [comment]
Gracias por el outline Erasmo, ¿cómo propones explorar los principios y conceptos básicos de redux/flux? Me late el porqué de la plática y creo que podría ser muy útil para todos.

**Comment by ErasmoLeon** [comment]
Mi idea era explicar un poco de teoría de flux(lo mas básico) y desde ahi explorar los principios redux con ejemplos mas prácticos para ver las principales diferencias, pros o contras, al final tendríamos armado un ejemplo un poco mas completo basado en redux, creo que eso da para 15- 20 min, abordar de manera practica flux igual extendería la platica, como ves? veo que hay mas platicas de Redux/React igual podríamos darle un giro para no repetir mucho.

**Comment by migonzalez** [comment]
Rob, Migcenel por acá :) 
Erasmo es parte del equipo de desarrollo acá y está entusiasmado en dar la plática el miércoles. Lo habíamos hablado antes para ver si entraba en Enero, igual avísame si logramos subirnos al tren.
Saludos!

**Comment by Sparragus** [comment]
Erasmo, por favor checa el mail que tienes en tu profile de GitHub :) Nos
urge tener la información de tu plática.

Richard Kaufman

2016-01-11 12:25 GMT-06:00 migonzalez <notifications@github.com>:
