### ISSUE TITLE
Polymer!

### ISSUE THREAD

**Issue by margotduek** [javascriptmx/chelajs#34]
Lo primero, explicar que es Polymer, para que se usa, porque se usa, cuando se usa y porque es mejor o peor que l@s otras librerías/frameworks.
Algo a lo que me he enfrentado es a la integración de Polymer con Backend, si es posible y no es tan complicado, pero no es tan obvio y al ser algo relativamente nuevo no existe tanta documentación. Pensé en poder hablar de si Ploymer fue implementado o no para aplicaciones completas con Backend, si es óptimo o no y como se debería de hacer.

**Comment by unRob** [comment]
Gracias por enviar tu propuesta, me late por dónde va, pero no sé si sea mucho material para 20 minutos, ¿qué opinas?

Asumo que por _Backend_ te refieres a un backend genérico, no a algún framework nuevo que todavía no conozco :sweat_smile:. Creo que, esta parte es la pregunta más interesante ¿Polymer es una buena herramienta para hacer clientes de un Backend/API? (en este sentido me parece que sería un buen fit para #14 @sparragus)

Por último, estaría buenazo que nos enviaras un outline de tu plática un poco mas concreto, en el [wiki](https://github.com/javascriptmx/chelajs/wiki#v0.0.x) hay algunos tips sobre lo que nos ayudaría a entender la idea detrás de la plática.

**Comment by Sparragus** [comment]
Creo que el tema está perfecto. Y que sería mejor aun si logramos juntar https://github.com/javascriptmx/chelajs/issues/30 y https://github.com/javascriptmx/chelajs/issues/14 en el mismo ChelaJS.

Para que ese ChelaJS quede bien epico, sería bueno ir viendo los outlines de todos desde ya. Así los speakers, @unRob y yo nos podemos juntar para discutir lo que quiere presentar cada uno, remover temas duplicados, y añadir temas que sirvan para juntar las tres pláticas.

Me emociona mucho! :D

**Comment by margotduek** [comment]
Creo que para no pasarme de los 20 minutos podría explicar rápidamente que es Polymer y hablar de lo que comenta @unRob, explicar porque si/no es una buena herramienta para Backend/API, ahorita lo pongo en el wiki. :bow:

**Comment by unRob** [comment]
¿Crees que nos puedas detallar un outline acá? Estamos empezando a revisar los temas para Enero, y me estaría buenazo si tienes chance de dar esta charla entonces.

**Comment by jeduan** [comment]
Margot está fuera de la ciudad hasta Julio.

**Comment by Sparragus** [comment]
Hola Margot! :D Estoy preparando la información del meetup y necesito un poquito de información de ti. Me ayudas con eso, por favor? :)

**Short Bio/Adword**
```
name: Graciela J. Script
url: https://twitter.com/chela_js
pic: https://pbs.twimg.com/profile_images/704544900990152704/r1XMV2Xv_400x400.jpg
bio: "Tu biografía en una oración"
```

Gracias!

**Comment by margotduek** [comment]
Hola!

name: Margot Duek
url: https://twitter.com/duekis
pic: https://www.facebook.com/photo.php?fbid=10154069820225528&set=a.427708330527.218976.645315527&type=3&theater
bio: Front end developer, amante de los algoritmos y la programación a bajo nivel.



Gracias! 
:)
