### ISSUE TITLE
Desarrollo de aplicaciones Desktop usando electron

### ISSUE THREAD

**Issue by Ikana** [javascriptmx/chelajs#36]
# Electron

Propongo compartir mi experiencia desarrollando aplicaciones de escritorio usando tecnologías web.

## Contenido
1. Aplicaciones de escritorio en la era web
2.  Electron
 * Soporte de OSes
 * Arquitectura
3. Usos
 * Ejemplos de aplicaciones desarrolladas con electron
 * Como usar paquetes nativos de node.js desde electron

## Demo

Demo sobre el uso de paquetes nativos de node, a través de frameworks como angular y backbone

**Comment by Sparragus** [comment]
Me gusta mucho el tema :) Hoy venía pensando en una app de desktop para gente que produce podcasts. :P

No entiendo esto:
  > Demo sobre el uso de paquetes nativos de node, a través de frameworks como angular y backbone

Suena como si nos vas a enseñar a usar npm, pero seguramente estoy equivocado. Nos explicas un poco más a que te refieres?

**Comment by Ikana** [comment]
Pues me refiero a que, usar algunas paquetes nativos de node en electron es transparente, pero hay algunos que es necesario recompilar con node-gyp y la verdad no existe mucha documentación al respecto.

**Comment by Sparragus** [comment]
Hey @Ikana! Que te parece dar esta plática para el ChelaJS de enero? Va a ser el 13 de enero en MercadoLibre.

**Comment by Ikana** [comment]
Para mi estaria perfecto ese dia, pero hasta mañana les puedo pasar el outline habria algun problema con eso??

**Comment by Sparragus** [comment]
No problem. Mañana le damos seguimiento al outline. :D

Richard Kaufman

**Comment by Ikana** [comment]
Bueno he estado depurando mi outline inicial y el final seria algo así:
* Aplicaciones de escritorio en la era web
* Alternativas a electron
* Aplicaciones desarrolladas en electron
* Arquitectura de Electron
* Demo de uso de paquetes nativos de node dentro de electron (estaba pensado en usar express)

**Comment by Sparragus** [comment]
Súper! :D Lo único que se me ocurre es cambiar un poco el demo, pero eso lo podemos ir trabajando en la marcha. Quizas un demo tipo hello-world sea más didáctico que enseñar a usar paquetes nativos (aun no sabemos ni hacer un app!). O quizas los demos pueden ser algunas de las aplicaciones que tu has hecho. Que piensas?

Pronto te escribiremos un email pidiendote algunos detalles. Como no tienes un email en tu perfil de Github, me lo pasas por aca o me lo escribes a richardbkaufman@gmail.com?
