### ISSUE TITLE
Practical UCD, Integrando buena usabilidad en el proceso de desarrollo

### ISSUE THREAD

**Issue by kouryuu** [javascriptmx/chelajs#37]
# ¿Qué es UCD?
*User Centered Design* es un proceso para diseñar interfaces humano-computadora que se enfoca en determinar las necesidades y habilidades de los usuarios finales.

# ¿Para qué?
Un sistema con buena usabilidad permite a los usuarios finales adquirir destreza para utilizar el sistema mucho más rápido y reducir el nivel de frustración al realizar tareas.

# Integrando con el ritmo actual de desarrollo
Actualmente los desarrollos de software se realizan mediante métodos ágiles (SCRUM, Xtreme Programming etc.) por lo que el integrar pruebas con usuarios y demás métodos de UCD requieren adaptarse a ciclos cortos y procesos iterativos.

# Propuesta

El objetivo de la plática es plantear diversos métodos que permiten desarrollar software considerando el maximizar la usabilidad; mediante técnicas tales como prototipos en papel, cuestionarios, entrevistas e incluso principios psicológicos (Gestalt).

**Comment by unRob** [comment]
¡Disculpa por el retraso en revisar esta propuesta! Me declaro incompetente al respecto y no veo muy bien cómo acomodar esta plática, ¿nos puedes echar la mano describiendo un poco mas minuciosamente el outline de la plática que tienes en mente Rodrigo?

**Comment by jeduan** [comment]
He visto buenas pláticas en Youtube del tema. ¿Hay alguna(s) que te gusten y nos puedas mostrar como inspiración?

**Comment by kouryuu** [comment]
Hola disculpen la demora, bien pues en general la plática se orienta a un problema en específico que es muy común al desarrollar interfaces gráficas.Esto es el usuario final no entiende y no sabe cómo usar el sistema de manera óptima y ocasiona muchas veces frustración y enojo.Actualmente muchas empresas de software invierten recursos y tiempo de desarrollo en pruebas de usabilidad.
Las pruebas de usabilidad nos permiten evaluar la interfaz y detectar fallas.
El objetivo de esta plática es que los desarrolladores y las empresas de desarrollo  de software conozcan distintas estrategias, que pueden aplicar en su ciclo de desarrollo.
He dado pláticas en varios eventos de desarrollo (ChilangoRails, DrupalCamp etc.), y soy desarrollador de varios años; en lo personal me agrada bastante Javascript (mucha gente lo considera de "juguete" pero creo que no lo conocen lo suficiente como para entender las bondades de un lenguaje funcional).

Respecto a los videos que propone @jeduan  hay uno bastante cómico y bueno de David Pogue un columnista de NY Times
[TED David Pogue](https://www.youtube.com/watch?v=NEjZt0y6OOw)

Otro muy cómico de un programa Noruego
[Medieval helpdesk](https://www.youtube.com/watch?v=pQHX-SjgQvQ&index=33&list=WL)

Unos slides muy útilies para entender más acerca de lo que es usabilidad 
[Top Ten Myths About Usability](http://measuringuserexperience.com/UsabilityMyths/UsabilityMyths.pdf)

Tengo aún más recursos que les puede servir sin embargo, considero que por el momento lo que les estoy dado es lo suficientemente introductorio para dar a entender de lo que se trata la plática.
Excelente dia y ¡nos veremos en el proximo ChelaJS!

**Comment by Sparragus** [comment]
Haha. No tienes idea el bien que me haría aprender a diseñar interfaces. Ahora mismo soy un desastre xD

El tema de tu plática me parece excelente y muy entretenido. Nos encantaría tener el próximo miércoles en ChelaJS con este tema. Siempre hablamos mucho código y nos olvidamos hablar de que el usuario sí ve.

¿Qué te parece?
Cheers!

**Comment by kouryuu** [comment]
@Sparragus claro! Si estoy pensando en dar mi plática desde la óptica de un desarrollador/project manager y quizá un pequeño *demo interactivo* (con la participación de los asistentes) de una técnica muy común y eficaz que es la creación de [*User Personas*](http://www.usability.gov/how-to-and-tools/methods/personas.html) ¿Qué les parece? [Aqui](http://slides.com/rodkings/deck-11) unos slides de una plática que di en ChilangoRails :grin: que obviamente voy a reescribir y enfocar más a el dia a dia de un desarrollador.

**Comment by Sparragus** [comment]
Súper! Estamos confirmando el lugar y tan pronto quede te aviso. Gracias!

Richard Kaufman

2016-02-23 22:21 GMT-06:00 Rodrigo Reyes <notifications@github.com>:

**Comment by Sparragus** [comment]
Dude. Ahora si estamos! :D Sorry por la mega tardanza. Coordinar ChelaJS depende de muchas cosas.

ChelaJS ya está confirmado para ser el miércoles 16 de marzo a las 7:30pm en SegundaManoMX. Aun estás in? :D

**Comment by kouryuu** [comment]
Si sin pedos, :smile: , no te apures si me imaginé además que organizaron NodeSchool (que por cierto asistiré)... entonces ya en la semana preparo todo para el 16.
:tada:

**Comment by Sparragus** [comment]
Awesome! :D Me pasas un email para enviarte unas cosas? Me puedes escribir a richardbkaufman@gmail.com.
