### ISSUE TITLE
React con Redux

### ISSUE THREAD

**Issue by cool-acid** [javascriptmx/chelajs#38]
Contar mi experiencia de por qué comencé a usar Redux en mi aplicación y explicar cómo funciona.
Mas o menos podría estar así...

* Por qué usar Redux/Flux/Reflux/etc...
* Por qué Redux y no [...otros]
* Los fundamentos de Redux
* Actions, Reducers, Store
* Redux con React
* Ejemplo

**Comment by jeduan** [comment]
+1 por el uso del spread operator en `[...otros]`

**Comment by cool-acid** [comment]
Hehehe, pensé que nadie se daría cuenta.

**Comment by unRob** [comment]
Me gusta, pero me gustaría saber la diferencia entre el punto 1 y 2. Estaría chido empezar con describir las funciones de un patrón de diseño de software, y porqué estos frameworks/implementaciones son una alternativa superior a seguir haciendo front-end con las patas. ¿Cómo ves?

Por tu experiencia en back-end, creo que hay insights interesantes al observar las diferencias entre lo que estamos acostumbrados a programar para un ciclo de request-response, y lo que se acomoda mejor al flujo de una interfaz.

**Comment by Sparragus** [comment]
@cool-acid Dude, estás in para dar la plática el miércoles 13 de enero? Redux es un tema que está muy hot right now! :D

**Comment by Sparragus** [comment]
Hey @cool-acid! :D Te animas a una plática de redux-middleware (o cualquier otro tema de redux) para el próximo miércoles? Nos encataría poder escuchar de tu experiencia :)

He estado viendo y usando mucho middleware y hay varios que están bien cool. Ejemplos:

https://github.com/agraboso/redux-api-middleware
https://github.com/reactjs/reselect (y junto a https://github.com/gaearon/normalizr está epic awesome)
https://github.com/tonyhb/redux-ui
https://github.com/erikras/redux-form

De nuevo, el tema está abierto. Middleware es una sugerencia.

¿Qué crees?

**Comment by Sparragus** [comment]
Hey dude, Rob te platicó?

ChelaJS va a ser el miércoles 16 de marzo a las 7:30pm en SegundaManoMX. Te animas? :D

**Comment by aralroca** [comment]
Esto son charlas o como va la cosa? Me gustaría ver una charla de Redux con React :+1:

**Comment by Sparragus** [comment]
Hola @aralroca! ChelaJS es un meetup mensual donde tres ponentes hablan de temas alrededor de JavaScript. Esto que vez es una propuesta aceptada que va a ser presentada este miércoles. Si no hiciste RSVP en http://www.meetup.com/javascriptmx/events/229297984/ aun puedes escuchar la plática por YouTube. El miércoles, alrededor de las 8:00pm (Ciudad de México) comenzamos el stream del evento. Puedes sintonizar acá: https://www.youtube.com/c/chelajs/live

Esperamos verte pronto! Saludos.

**Comment by aralroca** [comment]
Muchas gracjas @Sparragus 

Lo miraré desde aquí Barcelona, España.
