### ISSUE TITLE
Introduccion al Bitcoin

### ISSUE THREAD

**Issue by 99Percent** [javascriptmx/chelajs#39]
Hola, soy pionero en el uso de bitcoin desde 2011, de los primeros en Mexico.  Puedo dar una platica introductoria sobre bitcoin, sus ventajas, como funciona y como incorporar pagos de bitcoin en una pagina web con javascript.

**Comment by rogr** [comment]
+1

**Comment by gplnet** [comment]
+1

2015-12-16 17:15 GMT-05:00 Rogelio <notifications@github.com>:

**Comment by unRob** [comment]
Gracias por tu propuesta, David. Vi tu repo, pero me quedan dudas sobre la estructura de tu plática, me puedes echar la mano con un bosquejo de la misma?

**Comment by Sparragus** [comment]
@99Percent A @unRob y a mi nos gusta mucho el tema. :) Quisieramos que la presentaras el miércoles 13 de enero en ChelaJS.

Pero antes de aprobar la plática, nos gustaría ver un outline de tu plática. Nos puedes ayudar con eso para hoy por la noche?

**Comment by 99Percent** [comment]
hola, como ven este outline:

1. Introduccion muy breve de bitcoin y sus ventajas para pagos web (2 mins)
2. Video introductorio de bitcoin: https://www.youtube.com/watch?v=ceef71b0zSo
3. Introduccion al web wallet blockchain.info y su API 5 mins
4. Incorporar el wallet blockchain.info para recibir pagos web. Ejemplos en javascript. 10 mins
Preguntas y respuestas.

Tambien puedo hablar de su historia, historia de la moneda en general, como va a afectar la situacion financiera a nivel mundial, sobre bitcoin core (cliente oficial de bitcoin) etc, pero divagaria mucho de tema de javascript. No se si aun estarian interasados.

**Comment by kouryuu** [comment]
+1

**Comment by 99Percent** [comment]
Parece que muchos aun no saben siquiera lo que es bitcoin, por lo que la platica primero tendría que dedicarse a explicar lo que es, y por lo tanto divagaría del enfoque del grupo que es Javascript. Bueno a ver si dentro de un año...

**Comment by Sparragus** [comment]
@99Percent Quieres dar la plática el próximo miércoles en ChelaJS? :D

**Comment by Sparragus** [comment]
El outline que escribiste en https://github.com/javascriptmx/chelajs/issues/39#issuecomment-168847611 me parece bien.

**Comment by 99Percent** [comment]
Ok, preparo la plática para este miércoles. Saludos

**Comment by Sparragus** [comment]
Awesome! Ya agendamos. Hoy o mañana publicamos los detalles de donde va a
ser. Te los hago llegar luego.

Gracias! :D

Richard Kaufman

**Comment by Sparragus** [comment]
@99Percent Te paso los detalles del meetup: http://www.meetup.com/javascriptmx/events/232944760/

**Comment by Sparragus** [comment]
Hey @99Percent! Mañana es ChelaJS.  Hay algo en que te podamos ayudar para que tu pres mañana quede awesome?

Pregunta: que computadora piensas usar? Es que para conectarnos al proyector vamos a usar Apple TV. Si tienes una Macbook, es muy fácil es setup. Si usas Windows, podemos usar AirParrot: http://www.airsquirrels.com/airparrot/try/. Y si usas Ubuntu déjame saber y busco una solución.

Puedes encontrar los detalles del evento aquí: http://www.meetup.com/javascriptmx/events/232944760/

**Comment by 99Percent** [comment]
Voy a llevar laptop con Linux Mint (variante de Ubuntu). Necesito conectarla al proyector como si fuera monitor, y un apuntador con boton para next slide. Llego temprano para hacer pruebas.

**Comment by 99Percent** [comment]
Tambien haré una demostración de como mandar bitcoins de un smartphone a otro, si eso se pudiera filmar y proyectar estaría bien.

**Comment by Sparragus** [comment]
Vamos a poder conectarte al proyector (resolvimos lo del Apple TV) pero no
tenemos apuntador. Está bien?

Richard Kaufman

2016-08-02 10:46 GMT-05:00 David Noriega <notifications@github.com>:

**Comment by 99Percent** [comment]
si, a ver si consigo el apuntador
