### ISSUE TITLE
Ractive.js

### ISSUE THREAD

**Issue by jeduan** [javascriptmx/chelajs#4]
Y que la de @pateketrueke

**Comment by Carlangueitor** [comment]
+1 :+1:

**Comment by pateketrueke** [comment]
Pues sí, ahí estaré. :beers:

**Comment by pateketrueke** [comment]
> Por favor tengan en cuenta que las pláticas son en inglés solo por este evento [...]

@jeduan ¿qué tan cierto es eso? ¿a huevo debo rifarme el talk english-spoken?

**Comment by jeduan** [comment]
Eso es en mimosa, dude, la tuya será en Junio y en español.

**Comment by pateketrueke** [comment]
Malditos correos de antaño, ni los leo bien y me precipito recio.

**Comment by jeduan** [comment]
Gracias por tu plática @pateketrueke!
