### ISSUE TITLE
Relay & GraphQL

### ISSUE THREAD

**Issue by Arbolista** [javascriptmx/chelajs#40]
Optimización de API calls en una aplicación de javascript y/o móvil. Reconsiderando el diseño de RESTful APIs.

**Comment by Arbolista** [comment]
Me gustaría dar esta plática en Enero.

**Comment by unRob** [comment]
Me late la idea Eric, cuéntanos más sobre la estructura de tu plática. Me parece que es un tema bien importante y el asunto del impacto que herramientas como Relay y GraphQL tendrán sobre nuestras implementaciones y por lo tanto, otros clientes.

Por otro lado, alguna razón especial para querer dar la plática en enero?

**Comment by Arbolista** [comment]
Hola Roberto,

La puedo hacer en Febrero - talvez seria mejor porque voy meterme mas en el
asunto en enero. Ademas, me gustaria asistir un ChelaJS antes de hacer una
platica (solo he venido una vez - hace mas que 9 meses).

Estructura:

   - Que es Relay? Que es GraphQL?
   - Donde se usan?
   - Cuales son las diferencias entre Relay y Flux? Cual es la diferencia
   entre GraphQL y REST APIs? Cuales son las ventajas y desventajas de cada
   uno?
   - Un ejemplo de usar los dos juntos en un app.

Como ves?

Eric



El 21 de diciembre de 2015, 22:27, Roberto Hidalgo <notifications@github.com
> escribió:

> Me late la idea Eric, cuéntanos más sobre la estructura de tu plática. Me
> parece que es un tema bien importante y el asunto del impacto que
> herramientas como Relay y GraphQL tendrán sobre nuestras implementaciones y
> por lo tanto, otros clientes.
>
> Por otro lado, alguna razón especial para querer dar la plática en enero?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/40#issuecomment-166502490>
> .
>



-- 
Eric Hulburd

Oroeco.com <http://www.oroeco.com/>
Twitter: @oyecalifornia <https://twitter.com/oyecalifornia>
Ciudad de México

**Comment by Arbolista** [comment]
@unRob @jeduan La proxima meetup va ser el proximo miercoles? Me gustaria asistir y conocerles.

Eric

**Comment by Sparragus** [comment]
No. Sería el 13 de enero.

Richard Kaufman

2015-12-30 19:18 GMT-04:00 Arbolista <notifications@github.com>:

**Comment by Arbolista** [comment]
Ahh no vi que hay un RSVP en el Meetup esta noche, entonces supongo que no
puedo asistir.

Pues, si les interes y hay un spot disponible el proximo mes para hablar
del asunto, avisame.

Eric

El 30 de diciembre de 2015, 19:14, Richard B. Kaufman-López <
notifications@github.com> escribió:

> No. Sería el 13 de enero.
>
> Richard Kaufman
>
> 2015-12-30 19:18 GMT-04:00 Arbolista <notifications@github.com>:
>
> > @unRob <https://github.com/unRob> @jeduan <https://github.com/jeduan> La
> > proxima meetup va ser el proximo miercoles? Me gustaria asistir y
> > conocerles.
> >
> > Eric
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/javascriptmx/chelajs/issues/40#issuecomment-168093399>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/40#issuecomment-168102944>
> .
>



-- 
Eric Hulburd

Oroeco.com <http://www.oroeco.com/>
Twitter: @oyecalifornia <https://twitter.com/oyecalifornia>
Ciudad de México

**Comment by Sparragus** [comment]
Hey dude!
Estamos programando las pláticas de febrero y nos interesa mucho este tema. Qué te parece darlo en para el Chelajs de febrero?

**Comment by Sparragus** [comment]
@Arbolista: Lo has considerado? Estaría padrísimo tenerte la próxima semana hablando del tema. :) Es un mega trending topic. :D

**Comment by Arbolista** [comment]
Tan pronto! Pues si me gustaria. Por lo general, cuanto duran las charlas?
10 minutos? Y donde se ubicara el meetup?

Probablemente, lo que voy hacer es una evaluacion (ventajas, desventajas) y
mostrar unos ejemplos

Eric

2016-01-26 23:04 GMT-06:00 Richard B. Kaufman-López <
notifications@github.com>:

> @Arbolista <https://github.com/Arbolista>: Lo has considerado? Estaría
> padrísimo tenerte la próxima semana hablando del tema. :) Es un mega
> trending topic. :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/40#issuecomment-175400334>
> .
>



-- 
Eric Hulburd

Oroeco.com <http://www.oroeco.com/>
Twitter: @oyecalifornia <https://twitter.com/oyecalifornia>
Ciudad de México

**Comment by Sparragus** [comment]
La plática duraría 20 minutos, incluyendo las preguntas. El meetup sería en la Condesa, en las oficinas de Conekta.

Creo que antes de hacer la evaluación, hay que empezar un poco desde cero explicando que es Relay y GraphQL, y de ahi puedes continuar a explicar como funcionan (o como usarlos). Se hace muy interesante compararlo con Flux, y entonces la evaluación de ventajas y desventajas. Finalmente, si da tiempo dar ejemplos.

Como lo ves?

**Comment by Arbolista** [comment]
Me parece bien el formato.

La verdad es que yo estoy convertiendome de Angular a React, entonces no he
ocupado Flux. De lo que he leido, es el proximo paso de Flux. Pero puedo
leer un poco de las diferencias.

Entonces a las 7, les veo en las oficinas de Conekta.

El 27 de enero de 2016, 10:04, Richard B. Kaufman-López <
notifications@github.com> escribió:

> La plática duraría 20 minutos, incluyendo las preguntas. El meetup sería
> en la Condesa, en las oficinas de Conekta.
>
> Creo que antes de hacer la evaluación, hay que empezar un poco desde cero
> explicando que es Relay y GraphQL, y de ahi puedes continuar a explicar
> como funcionan (o como usarlos). Se hace muy interesante compararlo con
> Flux, y entonces la evaluación de ventajas y desventajas. Finalmente, si da
> tiempo dar ejemplos.
>
> Como lo ves?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/40#issuecomment-175711166>
> .
>



-- 
Eric Hulburd

Oroeco.com <http://www.oroeco.com/>
Twitter: @oyecalifornia <https://twitter.com/oyecalifornia>
Ciudad de México

**Comment by jeduan** [comment]
Para mi lo de Flux no es super necesario porque lo que entiendo es que GraphQL está más en la capa de modelos que ser un patrón de arquitectura.

@Arbolista Estaba organizando un hangout el Lunes 1/Feb para escuchar un draft de la platica y poderla pulir al máximo. ¿Te interesaría participar?

**Comment by Arbolista** [comment]
Sí. ya que no pude asistir el meetup pasado, sería bien tener un idea de
como funciona todo etc etc.

El lunes entonces.

**Comment by jeduan** [comment]
Perfecto, digamos de 7 a 7:30 te funciona? Si si, mándame tu correo.

**Comment by Sparragus** [comment]
@Arbolista Ya estas! :D Te vemos el próximo miércoles 3 de febrero en Conekta a las 7:30pm. Ahora necesito que me envies un email a richardbkaufman@gmail.com para poder enviarte más info del evento y poder hacerte unas preguntas.

Nos vemos pronto!

**Comment by Sparragus** [comment]
@Arbolista, es súper importante que nos escribas hoy. Escribeme un email a richardbkaufman@gmail.com. Tenemos que enviarte unas cosas por email.

**Comment by Arbolista** [comment]
Desculpa, pense que ya te escribi. Nos hablamos a las 7. eric@arbol.org

2016-01-27 15:22 GMT-06:00 Jeduan Cornejo <notifications@github.com>:

> Perfecto, digamos de 7 a 7:30 te funciona? Si si, mándame tu correo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/javascriptmx/chelajs/issues/40#issuecomment-175859828>
> .
>



-- 
Eric Hulburd

Oroeco.com <http://www.oroeco.com/>
Twitter: @oyecalifornia <https://twitter.com/oyecalifornia>
Ciudad de México
