### ISSUE TITLE
Enterprise Application Development

### ISSUE THREAD

**Issue by joeleduardo** [javascriptmx/chelajs#41]
La idea es presentar una fotografía actual de las oportunidades del segmento enterprise para el desarrollo de aplicaciones mobile con js y mencionar algunas herramientas de las que podemos echar mano (SAP, IBM, Kony) que actualmente se usan en el segmento y que representan buenos dividendos para los devs

**Comment by Sparragus** [comment]
Hey @joeleduardo!

Estamos programando las pláticas de febrero y le vemos potencial a este tema. Sin embargo, primero me gustaría pulir un poco más el tema y el outline antes de tomar una decisión.

Comenzemos por lo básico:
¿quien/cual es el segmento enterprise?
¿qué son herramientas enterprise?
¿qué es desarrollo enterprise?

Te pregunto por que soy totalmente ignorante de esos terminos. Y algo me dice que no soy el único.

Entonces está chido entrar a estudiar algunas de esas herramientas y conocerlas. Luego estaría interesante saber quien está usando esas herramientas y por qué.

Finalmente conocer las oportunidades que existen para los devs que manejan esas herramientas.

Crees que nos puedas preparar un outline de nuevo considerando todo eso y que la presentación debe ser de 20 minutos, incluyendo las preguntas?

**Comment by joeleduardo** [comment]
Hola que claro que si con gusto, contestando a tus preguntas:

¿Quién/cual es el segmento enterprise?
En méxico hay empresas como grupo modelo, nissan, volkswagen, SAP, ORACLE, IBM, Kony, etc. que son parte de este segmento y que de alguna manera requieren de aplicaciones/sistemas integrados a diferentes verticales y que no necesariamente son de dominio publico si no mas bien privado, por ej. volkswagen en su línea de producción tiene aplicaciones que arrojan información que es consumida por un framework basado en JS y presenta los KPIs a altos mandos de la empresa y que su vez puede interactuar con sistemas CRM, ERP, etc. (SAP/ORACLE).

¿Qué son herramientas enterprise?
Herramientas para el diseño, desarrollo y deploy de aplicaciones cerradas, que a su vez pueden ser integradas a un MDM (Mobile Device Managment) o EMM (Enterprise Mobility Manager) para la toma de decisiones del negocio (Si, como muy comercial pero eso es jeje)

¿Qué es desarrollo enterprise?
Desarrollo de aplicaciones tanto desktop como mobile cerradas que comúnmente se integran con  CRM´s, ERP´s.

¿Quienes están usando esas herramientas y porque?
Empresas como las que mencione en la primera pregunta y porque se integran de forma "fácil" a las operaciones de producción y distribución de bienes y servicios de una empresa (enterprise).

¿Oportunidades de los devs (js/web)?
En mi experiencia (un año y poquito más) existen un abanico de posibilidades ya que en ese segmento aun están viendo implementado movilidad (incluso desconocen el mundo dev convencional) y obviamente al requerir aplicaciones multiplaforma mucho del desarrollo es con tecnología web.

Ya cuento con una presentación al respecto es algo muy pero muy por encima por el tiempo pero creo puede hacerse un demo sin problema.

Espero haber sido lo mas claro posible.

Saludos.

**Comment by jeduan** [comment]
@joeleduardo Estoy organizando un hangout el Lunes 1/Feb para escuchar un draft de la platica y poderla pulir al máximo. ¿Te interesaría participar?

**Comment by Sparragus** [comment]
@joeleduardo Ya estas! :D Te vemos el próximo miércoles 3 de febrero en Conekta a las 7:30pm. Te vamos a estar escribiendo al email que tienes en tu perfil de GitHub para enviarte más información del evento y para hacerte unas preguntas.

Nos vemos pronto! :D

pd. Recuerda ver con @jeduan el tema del hangout. :)

**Comment by joeleduardo** [comment]
Claro que si, como a qué hora sería?

**Comment by jeduan** [comment]
Te queda como a las 7?
