### ISSUE TITLE
JXCore: Extend node with multithreading

### ISSUE THREAD

**Issue by jcebXD** [javascriptmx/chelajs#42]
El objetivo es explicar jxcore, las principales características que añade a node, y mostrar un ejemplo de como funciona en un ambiente del mundo real.

http://jxcore.com

El ejemplo va a ser un proceso conectado con net.socket a otro servidor y delegando entre uno y otro socket la conexión al servidor.

**Comment by Sparragus** [comment]
Hey @julianceballos! Nos puedes preparar un breve outline de lo que sería tu presentación? Crees que sea algo que puedas presentar para el próximo Chelajs el 3 de febrero?

**Comment by julianceballos** [comment]
Hola @Sparragus sin duda puede ser presentado el próximo 3 de febrero, básicamente lo que queremos compartir es un caso practico, de como nosotros lo usamos, para con el proceso padre mantener un servidor http que inicializa los hilos, y al recibir llamadas http, decide a que hilo mandar el procesamiento de la tarea solicitada y cada hilo reporta su resultado al padre por pase de mensajes.

**Comment by Sparragus** [comment]
Me gusta por donde va el outline, pero creo que hay que reorganizarlo un poco. Muchos nunca hemos escuchado que es JXCore (incluyéndome!) entonces hay que comenzar desde un intro de JXCore.

Quizas puedes comenzar explicando como node.js opera en un single thread. Entonces ahi introduces JXCore y lo comparas. Puedes seguir introduciendo casos ejemplos que sirvan para entender cuando queremos usarlo. Nos enseñas features que hacen que JXCore esté epic. Y de ahi puedes ir cerrando con use-cases en tu compañía y ejemplos de mundo real.

Como lo ves?

**Comment by jeduan** [comment]
@julianceballos Estoy organizando un hangout el Lunes 1/Feb para escuchar un draft de la platica y poderla pulir al máximo. ¿Te interesaría participar?

**Comment by julianceballos** [comment]
Hola @jeduan y @Sparragus considero, que sería mejor idea darla en el siguiente, ya que ahora, me encuentro con timeline un poco apretado en el trabajo. Como ven?

**Comment by Sparragus** [comment]
Va dude. No problem. La próxima vez esperamos poder anunciar las pláticas con más tiempo. :) Minetras dejamos esta on hold.

**Comment by julianceballos** [comment]
Si, concuerdo con que queremos que salga chingona, la planearé para el próximo mes y así añadirá más valor a la comunidad.

**Comment by Sparragus** [comment]
¡Hey @julianceballos! ¿Aun contamos con tu plática de JXCore para el próximo ChelaJS en Conekta? Nos encaría que puedas acompañarnos como presentador. :)

El evento va a ser el miércoles 6 de abril a las 7:30pm en Conekta. ¿Qué te parece? :)

**Comment by julianceballos** [comment]
Que onda, si claro cuentan conmigo. Saludos.

**Comment by Sparragus** [comment]
Yeah! :D Gracias :)
