### ISSUE TITLE
CloudinoJS

### ISSUE THREAD

**Issue by SergioMartinezP** [javascriptmx/chelajs#44]
Un problema al hacer prototipos para IoT en Arduino tiene que ver con la complejidad de conectarse a Internet, Cloudino es una propuesta para eliminar esa complejidad.
-Arduino para IoT - Shields, espacio requerido para el Stack de red.
-ESP8266 al rescate - descargar el stack de red a un procesador secundario
-IoT hecho fácil con Cloudino - presentación de la iniciativa Cloudino
-cloudino.io - Servicio en la nube para programar y controlar cloudinos
-Cloudino sin Arduino - Puertos del ES8266 que se pueden usar sin conectar un Arduino
-Interprete de JavaScript en Cloudino - La forma de programar el ESP8266 
-Ejemplos:
--Leer, escribir puertos de Cloudino
--Timers
--Envío y recepción de mensajes a la nube

**Comment by Sparragus** [comment]
Hey @SergioMartinezP! Gracias por la propuesta.

El tema suena muy hardware y aun no logro entender como JS juega un papel. Visité la página de Cloudino y tampoco tengo claro qué es.

Me ayudas elaborando un poco más en el tema?

**Comment by SergioMartinezP** [comment]
A si es, basicamente es Hardware para IoT, usamos el ESP8266 como un puente entre Protocolos de Internet como MQTT con un proyecto hecho en Arduino.
La intensión de mostrarlo aquí es porque en la programación del ESP8266 incluimos un interprete de scripts con sintaxis tipo JavaScript; esto porque el ESP8266 tiene 6 Puertos Digitales y uno analógico. 
Es decir, con el puro ESP8266 podemos interactuar con estos puertos, ejemplo:

var msg;
require("GPIO");
pinMode(4, OUTPUT);
require("Cloudino");

Cloudino.on('led',function(msg){
  if (msg == 'on') {
    digitalWrite(4, HIGH);
  } else {
    digitalWrite(4, LOW);
    Cloudino.print('Apagado');
  }
});

Va a escuchar en "internet" hasta que llegue un mensaje 'led' y entonces evaluará el con el contenido, si es 'on' va a enviar corriente al pin 4 del chip, cualquier otra cosa enviará tierra al pin 4 y si como conexión a internet se utiliza cloudino.io, en la consola de este dispositivo en la nube se imprimirá 'Apagado'

**Comment by rogr** [comment]
Creo esta charla esta mas enfocada para NodeBots @jurasec.

**Comment by jurasec** [comment]
Si, de hecho la podrían presentar sin problemas el siguiente meetup.

**Comment by Sparragus** [comment]
@SergioMartinezP Gracias por la propuesta dude, pero creo que el tema es mejor para NodeBots. NodeBots quiere celebrar Arduino Day el 2 de abril. Creo que es un día perfecto para esta plática. Sigue la comunicación con @jurasec para que puedan coordinar la plática. De todas formas, gracias por la propuesta,

Abrazo!

**Comment by SergioMartinezP** [comment]
ok, Gracias, de hecho mi Jefe ya esta con una propuesta para ese día.

Saludos.
