### ISSUE TITLE
Data viz con JS

### ISSUE THREAD

**Issue by bleedingxedge** [javascriptmx/chelajs#5]
Evaluando la mejor herramienta para cada uso, dependiendo de tus necesidades.

**Comment by blacknash** [comment]
Se mostrarían cosas como D3 , Springy, GDC y así ?

**Comment by bleedingxedge** [comment]
@blacknash mas que enfocarse en un framework, enfocarse en como elegir el framework para cada situacion. Mas que hablar de d3, hablar de SVG y Canvas

**Comment by bleedingxedge** [comment]
@blacknash o por ahi se me ocurrió. Igual si tienes sugerencias: bienvenidas.

**Comment by szabadgyalog** [comment]
https://blog.safaribooksonline.com/2012/04/17/using-html5-canvas-vs-svg/ https://dev.opera.com/articles/svg-or-canvas-choose/

**Comment by szabadgyalog** [comment]
¿Qué gráficas ha hecho la gente en el DF con estas librerías?

**Comment by szabadgyalog** [comment]
¿Alguien por aquí ha dibujado algo con librerías de DataViz? C'mon :smiley:

**Comment by jeduan** [comment]
Si te refieres a cosas como D3/Chart.js si, se que lo usan en la oficina de @bleedingxedge @blacknash y en muchos otros lugares que no se pararon aquí de domingo a lunes. No se si tenias alguna pregunta más específica?

**Comment by szabadgyalog** [comment]
Al menos a mí, me daría gusto ver las gráficas que han hecho estas personas que mencionas.

O que ha hecho cualquier otra persona que se para por aquí.

**Comment by jeduan** [comment]
No hay que perder de vista que este repo es para proponer pláticas para el evento mensual ChelaJS, por lo que probablemente es algo que tiene considerado @bleedingxedge para cuando de su plática (probablemente en el de Julio).
¿Tu quieres proponer alguna plática?

**Comment by szabadgyalog** [comment]
Tengo mucho interés en ver las gráficas que ha hecho la gente que se para por aquí. Hasta el momento no he visto nada. ¿Por qué? :smiley:

**Comment by jeduan** [comment]
Por favor lee el README del repo.

Este no es el medio adecuado para pedir que otras personas te muestren trabajo.
Es el medio adecuado si quieres compartir algo con la comunidad en un evento de [ChelaJS](http://meetup.com/chelajs)
Cerrando el issue.
