### ISSUE TITLE
ClojureScript

### ISSUE THREAD

**Issue by jeduan** [javascriptmx/chelajs#6]
Impartida por @nez

 - Cómo integrarlo con gulp/grunt
 - core de lisp
 - base pequeña para que puedan empezar a usar.

**Comment by MachinesAreUs** [comment]
+1

**Comment by jeduan** [comment]
Explicitamente prohibí empezar la plática con la frase "A mi me caga JavaScript pero…". por culpa de @MachinesAreUs 

Usarla a la mitad sigue permitido

**Comment by MachinesAreUs** [comment]
LoL

**Comment by pateketrueke** [comment]
Mira @iamedu

**Comment by iamedu** [comment]
+1

**Comment by MachinesAreUs** [comment]
Ah, mira @jeduan lo que me encontré :smiling_imp: :stuck_out_tongue_closed_eyes: 
https://github.com/MachinesAreUs/elm_playground/blob/master/chelaJs5/slides.elm#L59

**Comment by jeduan** [comment]
LOL :trollface:

**Comment by Siedrix** [comment]
@nez Estamos agendando las pláticas para el evento de la proxima semana. Todavia sigues con interes y disponibilidad de dar esta plática?

**Comment by jeduan** [comment]
Gracias por tu plática @nez

**Comment by Sparragus** [comment]
@nez, Puedes subir tu presentación? No pude asistir pero me gustaría ver
los slides :)

Richard Kaufman
