### ISSUE TITLE
Aprendiendo de ES3

### ISSUE THREAD

**Issue by Siedrix** [javascriptmx/chelajs#60]
name: Daniel Zavala
url: https://siedrix.com
pic: https://pbs.twimg.com/profile_images/707929708273340418/pggBldks.jpg
bio: “JS dev, trabajando den latteware.io"

En la época de ES3 ya hacíamos apps bastante grandes e interactivas con JS con mucho menos tooling del que tenemos hoy en día. Me gustaría hablar un rato de funciones y eventemitter y como los usábamos en esa época.

**Comment by Sparragus** [comment]
Suena súper bien! :D Vamos a agendar esta plática para el 1 de junio. El ChelaJS de junio va a ser en el Centro de Cultura Digital, de 7-10pm.

Luego te estaremos pasando más detalles sobre el evento.

Cualquier pregunta que tengas, o si necesitas algo para tu presentación, déjanos saber y con gusto te ayudamos dude.

Gracias!
