### ISSUE TITLE
Algunos Tópicos de seguridad en Aplicaciones Web

### ISSUE THREAD

**Issue by SergioMartinezP** [javascriptmx/chelajs#7]
El objetivo sería hablar de Inyecciones, XSS y CSRF, por qué ocurren y sugerencias de mitigación

**Comment by jeduan** [comment]
:+1: alguna libreria en especial?

**Comment by SergioMartinezP** [comment]
No, mas bien propongo, de manera similar la que di en Campus, pero por tiempo limitado a esos tres riesgos. Basado en el Top 10 de OWASP

**Comment by unRob** [comment]
Me late esta plática, creo que sería buenaza para la comunidad at large.

**Comment by jurasec** [comment]
+1

**Comment by omarsharim** [comment]
+1

**Comment by jeduan** [comment]
asignado para ChelaJS Junio

**Comment by jeduan** [comment]
Gracias por tu plática @SergioMartinezP !

**Comment by SergioMartinezP** [comment]
Gracias a ustedes, están haciendo un muy buen trabajo con la comunidad! 

Y por si les preguntan la presentación está en: http://www.slideshare.net/superserch/chela-securitynode
