### ISSUE TITLE
¿Cuánto cobrar por nuestro trabajo?

### ISSUE THREAD

**Issue by cool-acid** [javascriptmx/chelajs#8]
O cuanto pedir de sueldo. Creo que es algo que luego nos falla.

**Comment by jeduan** [comment]
:+1: Aunque como dicen, siempre depende. ¿Sería interesante entender cuánto pagan en otros lados?

**Comment by nez** [comment]
estaria chido que quien la de, explique los conceptos de oferta y demanda

**Comment by unRob** [comment]
@bmedinab ¿Qué se te ocurre?

**Comment by unRob** [comment]
Por falta de interés marcó esta plática como comida para el garbage collector que viene en 30 días después de la publicación de este label. Si alguien desea adoptarla, ¡manda un outline!
