### ISSUE TITLE
React.js

### ISSUE THREAD

**Issue by Sparragus** [javascriptmx/chelajs#9]
Puedo dar un plática de React.js. La realidad es que llevo como un mes usándolo y me encanta. Creo que me siento cómodo dando una pláctica sobre las cosas básicas, el lenguaje, JSX, ES6, y la filosofía de React y cosas así.

No estaría comparando con Angular o algún otro framework, por que no conozco ninguno otro además de React.

¿Hay interes?

**Comment by jeduan** [comment]
Lo estas usando con flux, backbone o qué usas para las otras capas?

**Comment by Sparragus** [comment]
El próximo paso va a ser Flux, pero aun no le he entrado a nada de eso.

Uso Webpack para el build, Babel para ES6, Less para el CSS, Express y
MongoDB para el backend.

Realmente el talk sería algo muy intro por que aun estoy en el nivel básico
de React.

Richard Kaufman

**Comment by unRob** [comment]
¿Cómo ves armarte esta plática para Octubre @Sparragus? Me interesa mucho tus insights después de pasar rato aprendiendo el framework, ¿qué se te ocurre?

**Comment by Sparragus** [comment]
Dude, no se. Creo que alguien la puede mucho mejor que yo. xD Si la doy, me
quedaría muy en lo básico. Tu me dices. *Intro* a React? Algo básico, para
motivar a la gente.

Sobre insights, pues no tengo mucho. Y la razón es básica. React es el
primer framework que uso para hacer frontend. O sea, antes de eso, hacía
más backend. Entonces no puedo comparar a React con los demás frameworks.

Eso si, hay muchas cosas de React que sin comparación me digo yo mismo "de
verdad hace mucho sentido hacer el front así". Por ejemplo, usar funciones
puras. Eso te da un chingo de beneficios.

A mi me encanta presentar xD Del tema que sea doy una pres :D Let me know.

Richard Kaufman

2015-08-27 2:40 GMT-05:00 Roberto Hidalgo <notifications@github.com>:

**Comment by bleedingxedge** [comment]
Creo que @dbautistav puede dar esta plática para noviembre

**Comment by unRob** [comment]
Mark-to-sweep por inactividad. Este issue se cerrará en 30 días salvo que se presente un outline para el mismo.
